#include "core/Application.h"

#include "core/Constants.h"
#include "core/Platform.h"
#include "core/Screenshot.h"
#include "core/WebPersistence.h"
#include "physics/Lagrange.h"
#include "ui/UI.h"
#include "EmbeddedShaders.h"   // auto-generated by CMake from shaders/*.glsl
#include "imgui/imgui.h"
#include "imgui/backends/imgui_impl_glfw.h"
#include "imgui/backends/imgui_impl_opengl3.h"

#ifdef SOLARSYSTEM_BUILD_WEB
#  include <emscripten.h>
#  include <emscripten/html5.h>
#endif

#include <algorithm>
#include <chrono>
#include <cmath>
#include <ctime>
#include <filesystem>
#include <iostream>
#include <string>

namespace
{
// Trail sampling tuning.
constexpr size_t kTrailHistoryCapacity = 512;
constexpr float  kMinimumTrailStepWU   = 0.2f;
constexpr float  kTrailTeleportJumpWU  = 100.0f;

// Procedural ring mesh tuning.
constexpr int    kRingSegmentCount   = 64;
constexpr float  kRingInnerRadius    = 1.0f;
constexpr float  kRingOuterRadius    = 1.5f;
constexpr float  kRingScaleMultiplier = 1.5f;

// Camera and projection defaults.
// Cinematic 3/4 angle from the upper-front-right; matches Camera::reset().
const     glm::vec3 kInitialCameraPosition{ 220.0f, 160.0f, 280.0f };
constexpr float     kInitialCameraYaw   = -128.0f;
constexpr float     kInitialCameraPitch = -24.0f;
constexpr float  kProjectionNearPlane     = 0.01f;
constexpr float  kProjectionFarPlane      = 10000.0f;

// Scratch-vector reserve (prevents reallocations during typical "Add Planet" sessions).
constexpr size_t kBodiesReserveCapacity = 16;

// MSAA samples used by the offscreen scene FBO. 4 is the sweet spot for
// line aliasing — 2× still shows visible stair-stepping on the grid, 8× is
// memory-wasteful in browsers without a perceptible quality bump.
constexpr int    kSceneMsaaSamples         = 4;

// Path prediction tuning.
constexpr int    kPredictionSampleCount    = 500;
// Refresh ~12×/s. Higher rate gives the line a "rolling" feel instead of
// snapping, which matters most in orbital camera where the body sits at the
// screen center and any tip jump is impossible to miss.
constexpr int    kPredictionRefreshFrames  = 5;
const     glm::vec3 kPredictionColor{ 0.55f, 0.95f, 1.0f };

// Visual ring color.
const     glm::vec3 kSaturnRingColor{ 0.90f, 0.85f, 0.70f };

// Deep-space dark-blue ImGui palette tuned for the Solar System's black
// skybox + bright planet sprites. Applied once at startup; user-tunable
// pieces (GUI scale, VSync) keep their existing paths.
void applyDarkSpaceTheme()
{
    ImGuiStyle& style = ImGui::GetStyle();
    ImGui::StyleColorsDark();  // base — we override the chromatic pieces

    // Rounding — softer-than-default corners give the dock-style panels
    // a less utilitarian look without becoming bubbly.
    style.WindowRounding    = 4.0f;
    style.ChildRounding     = 4.0f;
    style.FrameRounding     = 4.0f;
    style.PopupRounding     = 4.0f;
    style.ScrollbarRounding = 4.0f;
    style.GrabRounding      = 4.0f;
    style.TabRounding       = 4.0f;

    // Padding & spacing — slightly more generous so Inter at 16px breathes.
    style.WindowPadding    = ImVec2(10.0f, 8.0f);
    style.FramePadding     = ImVec2(8.0f, 4.0f);
    style.ItemSpacing      = ImVec2(8.0f, 6.0f);
    style.ItemInnerSpacing = ImVec2(6.0f, 4.0f);

    // Palette — every chromatic ImGuiCol that shows up in the actionbar +
    // panels gets a deep-blue tint; accents (slider grabs, checkmarks)
    // pop in lighter cyan so they read against the dark fill.
    ImVec4* c = style.Colors;
    c[ImGuiCol_Text]                  = ImVec4(0.86f, 0.88f, 0.94f, 1.00f);
    c[ImGuiCol_TextDisabled]          = ImVec4(0.45f, 0.50f, 0.60f, 1.00f);
    c[ImGuiCol_WindowBg]              = ImVec4(0.03f, 0.047f, 0.086f, 0.94f);
    c[ImGuiCol_ChildBg]               = ImVec4(0.03f, 0.047f, 0.086f, 0.50f);
    c[ImGuiCol_PopupBg]               = ImVec4(0.04f, 0.06f, 0.10f, 0.94f);
    c[ImGuiCol_Border]                = ImVec4(0.12f, 0.16f, 0.24f, 0.50f);
    c[ImGuiCol_FrameBg]               = ImVec4(0.05f, 0.07f, 0.12f, 0.94f);
    c[ImGuiCol_FrameBgHovered]        = ImVec4(0.10f, 0.15f, 0.25f, 1.00f);
    c[ImGuiCol_FrameBgActive]         = ImVec4(0.15f, 0.22f, 0.36f, 1.00f);
    c[ImGuiCol_TitleBg]               = ImVec4(0.04f, 0.06f, 0.10f, 1.00f);
    c[ImGuiCol_TitleBgActive]         = ImVec4(0.06f, 0.10f, 0.18f, 1.00f);
    c[ImGuiCol_TitleBgCollapsed]      = ImVec4(0.04f, 0.06f, 0.10f, 0.75f);
    c[ImGuiCol_MenuBarBg]             = ImVec4(0.04f, 0.06f, 0.10f, 1.00f);
    c[ImGuiCol_Header]                = ImVec4(0.16f, 0.28f, 0.50f, 0.50f);
    c[ImGuiCol_HeaderHovered]         = ImVec4(0.20f, 0.35f, 0.62f, 0.80f);
    c[ImGuiCol_HeaderActive]          = ImVec4(0.25f, 0.45f, 0.75f, 1.00f);
    c[ImGuiCol_Button]                = ImVec4(0.12f, 0.18f, 0.30f, 0.80f);
    c[ImGuiCol_ButtonHovered]         = ImVec4(0.20f, 0.30f, 0.50f, 1.00f);
    c[ImGuiCol_ButtonActive]          = ImVec4(0.30f, 0.45f, 0.70f, 1.00f);
    c[ImGuiCol_CheckMark]             = ImVec4(0.40f, 0.75f, 1.00f, 1.00f);
    c[ImGuiCol_SliderGrab]            = ImVec4(0.30f, 0.50f, 0.80f, 1.00f);
    c[ImGuiCol_SliderGrabActive]      = ImVec4(0.40f, 0.65f, 0.95f, 1.00f);
    c[ImGuiCol_ScrollbarBg]           = ImVec4(0.04f, 0.06f, 0.10f, 0.60f);
    c[ImGuiCol_ScrollbarGrab]         = ImVec4(0.12f, 0.18f, 0.30f, 1.00f);
    c[ImGuiCol_ScrollbarGrabHovered]  = ImVec4(0.20f, 0.30f, 0.50f, 1.00f);
    c[ImGuiCol_ScrollbarGrabActive]   = ImVec4(0.30f, 0.45f, 0.70f, 1.00f);
    c[ImGuiCol_Separator]             = ImVec4(0.12f, 0.18f, 0.30f, 0.50f);
    c[ImGuiCol_SeparatorHovered]      = ImVec4(0.20f, 0.30f, 0.50f, 0.80f);
    c[ImGuiCol_SeparatorActive]       = ImVec4(0.30f, 0.45f, 0.70f, 1.00f);
    c[ImGuiCol_ResizeGrip]            = ImVec4(0.12f, 0.18f, 0.30f, 0.50f);
    c[ImGuiCol_ResizeGripHovered]     = ImVec4(0.20f, 0.30f, 0.50f, 0.80f);
    c[ImGuiCol_ResizeGripActive]      = ImVec4(0.30f, 0.45f, 0.70f, 1.00f);
    c[ImGuiCol_Tab]                   = ImVec4(0.08f, 0.13f, 0.22f, 1.00f);
    c[ImGuiCol_TabHovered]            = ImVec4(0.20f, 0.30f, 0.50f, 1.00f);
}
} // namespace

//----------------------------------------------------------------------------
// Static callbacks
//----------------------------------------------------------------------------

Application* Application::fromWindow(GLFWwindow* window)
{
    return static_cast<Application*>(glfwGetWindowUserPointer(window));
}

void Application::mouseCallback(GLFWwindow* window, double xpos, double ypos)
{
    Application* app = fromWindow(window);
    if (app == nullptr) return;

    if (app->firstMouseEvent_)
    {
        app->lastMouseX_      = static_cast<float>(xpos);
        app->lastMouseY_      = static_cast<float>(ypos);
        app->firstMouseEvent_ = false;
    }

    const float xOffset = static_cast<float>(xpos) - app->lastMouseX_;
    const float yOffset = app->lastMouseY_ - static_cast<float>(ypos);
    app->lastMouseX_    = static_cast<float>(xpos);
    app->lastMouseY_    = static_cast<float>(ypos);

    if (app->uiManager_.isRightMousePressed(window))
    {
        app->camera_.processMouseMovement(xOffset, yOffset);
    }
}

void Application::scrollCallback(GLFWwindow* window, double /*xoffset*/, double yoffset)
{
    Application* app = fromWindow(window);
    if (app == nullptr || ImGui::GetIO().WantCaptureMouse) return;

    app->camera_.processKeyboard(yoffset > 0 ? GLFW_KEY_W : GLFW_KEY_S, 0.1f);
}

void Application::windowFocusCallback(GLFWwindow* window, int focused)
{
    Application* app = fromWindow(window);
    if (app == nullptr) return;

    if (focused == GLFW_FALSE)
    {
        // Only auto-pause if the simulation is actively running and isn't
        // already paused (so manual pauses don't get clobbered on resume).
        if (app->appState_ == AppState::Running && !app->physics_.paused)
        {
            app->physics_.paused = true;
            app->wasAutoPaused_  = true;
        }
    }
    else if (app->wasAutoPaused_)
    {
        app->physics_.paused = false;
        app->wasAutoPaused_  = false;
    }
}

void Application::windowCloseCallback(GLFWwindow* window)
{
    Application* app = fromWindow(window);
    if (app == nullptr) return;

    if (app->appState_ == AppState::Running)
    {
        // Defer the close until the user confirms.
        glfwSetWindowShouldClose(window, GLFW_FALSE);
        app->openQuitPopup_ = true;
    }
}

void Application::framebufferSizeCallback(GLFWwindow* window, int width, int height)
{
    glViewport(0, 0, width, height);
    Application* app = fromWindow(window);
    if (app == nullptr) return;
    app->sceneFbo_.resize(width, height);
    app->sceneResolveFbo_.resize(width, height);
    app->bloomPingFbo_.resize(width / 2, height / 2);
    app->bloomPongFbo_.resize(width / 2, height / 2);
}

//----------------------------------------------------------------------------
// Construction / destruction
//----------------------------------------------------------------------------

Application::Application(int windowWidth, int windowHeight, const char* title)
    : window_(windowWidth, windowHeight, title)
    , camera_(kInitialCameraPosition)
    , bodyShader_           (embedded_shaders::VertexShader,           embedded_shaders::FragmentShader)
    , gridShader_           (embedded_shaders::GridVertexShader,       embedded_shaders::GridFragmentShader)
    , trailShader_          (embedded_shaders::TrailVertexShader,      embedded_shaders::TrailFragmentShader)
    , skyShader_            (embedded_shaders::SkyVertexShader,        embedded_shaders::SkyFragmentShader)
    , ringShader_           (embedded_shaders::RingVertexShader,       embedded_shaders::RingFragmentShader)
    , bloomBlurShader_      (embedded_shaders::FullscreenQuadVertexShader, embedded_shaders::BloomBlurFragmentShader)
    , bloomCompositeShader_ (embedded_shaders::FullscreenQuadVertexShader, embedded_shaders::BloomCompositeFragmentShader)
    , atmosphereShader_     (embedded_shaders::AtmosphereVertexShader,     embedded_shaders::AtmosphereFragmentShader)
    , sceneFbo_             (windowWidth,     windowHeight,     true,  kSceneMsaaSamples)
    , sceneResolveFbo_      (windowWidth,     windowHeight,     false, 1)
    , bloomPingFbo_         (windowWidth / 2, windowHeight / 2, false)
    , bloomPongFbo_         (windowWidth / 2, windowHeight / 2, false)
    , physics_()
    , uiManager_()
    , grid_(10000.0f, 200, 0.0f)
{
    bodies_.reserve(kBodiesReserveCapacity);

    GLFWwindow* glfwWindow = window_.getGLFWwindow();
    glfwSetWindowUserPointer(glfwWindow, this);
    glfwSetFramebufferSizeCallback(glfwWindow, framebufferSizeCallback);
    glfwSetCursorPosCallback(glfwWindow,       mouseCallback);
    glfwSetScrollCallback(glfwWindow,          scrollCallback);
    glfwSetWindowFocusCallback(glfwWindow,     windowFocusCallback);
    glfwSetWindowCloseCallback(glfwWindow,     windowCloseCallback);
    glfwSetInputMode(glfwWindow, GLFW_CURSOR, GLFW_CURSOR_NORMAL);

    // HiDPI: the constructor's windowWidth/Height are window units; the actual
    // pixel framebuffer may differ. Resize FBOs to match the framebuffer.
    int initialFbWidth = 0, initialFbHeight = 0;
    glfwGetFramebufferSize(glfwWindow, &initialFbWidth, &initialFbHeight);
    if (initialFbWidth != windowWidth || initialFbHeight != windowHeight)
    {
        sceneFbo_.resize(initialFbWidth, initialFbHeight);
        sceneResolveFbo_.resize(initialFbWidth, initialFbHeight);
        bloomPingFbo_.resize(initialFbWidth / 2, initialFbHeight / 2);
        bloomPongFbo_.resize(initialFbWidth / 2, initialFbHeight / 2);
    }

    glEnable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
#ifndef SOLARSYSTEM_BUILD_WEB
    // Desktop drivers may require this flag to honor multisample renderbuffer
    // coverage. GLES3 / WebGL2 don't expose GL_MULTISAMPLE — it's implicit
    // whenever an FBO has a multisample attachment, so we skip the call there.
    glEnable(GL_MULTISAMPLE);
#endif

    createAuxiliaryBuffers();
    lagrangeMesh_.rebuild(1.0f);  // unit-radius icosahedron, scaled per L marker
    // Bodies are deferred to startSimulation() — the menu screen runs first
    // and only loads the default solar system when the user clicks Start.

    ImGui::CreateContext();

    // Load Inter Regular (bundled in third_party/fonts/, copied next to the
    // exe by the CMake POST_BUILD step). Falls back gracefully to the
    // built-in ProggyClean if the TTF can't be found.
    ImGuiIO& io = ImGui::GetIO();
    const ImFont* interFont = io.Fonts->AddFontFromFileTTF(
        "fonts/Inter-Regular.ttf", 16.0f);
    if (interFont == nullptr)
    {
        std::cerr << "Warning: fonts/Inter-Regular.ttf not found — falling "
                     "back to ImGui's default font.\n";
    }

    applyDarkSpaceTheme();

    ImGui_ImplGlfw_InitForOpenGL(glfwWindow, true);
#ifdef SOLARSYSTEM_BUILD_WEB
    // WebGL2's GLSL parser only accepts GLSL ES 3.00 — and ImGui's own
    // internal vertex/fragment uses in/out qualifiers that need at least
    // 300 es.
    ImGui_ImplOpenGL3_Init("#version 300 es");
#else
    ImGui_ImplOpenGL3_Init("#version 330");
#endif

    glfwSwapInterval(uiManager_.vsync ? 1 : 0);

    // Mobile-friendly defaults: drop MSAA on touchscreens to keep the frame
    // budget reasonable. The user can re-enable in Settings; rebuildSceneFbo
    // will be triggered via the dirty flag.
    if (platform::isMobileDevice())
    {
        uiManager_.msaaEnabled = false;
        uiManager_.msaaDirty   = true;
    }

#ifdef SOLARSYSTEM_BUILD_WEB
    // Register touch handlers. The canvas selector "#canvas" matches the
    // shell.html element. EM_FALSE for use_capture (let bubble phase fire so
    // ImGui's synthetic mouse events still reach the canvas first).
    emscripten_set_touchstart_callback ("#canvas", this, EM_FALSE, &Application::touchStartCallback);
    emscripten_set_touchmove_callback  ("#canvas", this, EM_FALSE, &Application::touchMoveCallback);
    emscripten_set_touchend_callback   ("#canvas", this, EM_FALSE, &Application::touchEndCallback);
    emscripten_set_touchcancel_callback("#canvas", this, EM_FALSE, &Application::touchCancelCallback);
#endif
}

Application::~Application()
{
    destroyAuxiliaryBuffers();
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
}

//----------------------------------------------------------------------------
// Public API
//----------------------------------------------------------------------------

#ifdef SOLARSYSTEM_BUILD_WEB
void Application::emscriptenTick(void* arg)
{
    static_cast<Application*>(arg)->tick();
}

void Application::syncWebCanvasSize()
{
    double cssWidth = 0.0, cssHeight = 0.0;
    if (emscripten_get_element_css_size("#canvas", &cssWidth, &cssHeight) != EMSCRIPTEN_RESULT_SUCCESS)
    {
        return;
    }

    const double dpr     = emscripten_get_device_pixel_ratio();
    const int    targetW = static_cast<int>(cssWidth  * dpr);
    const int    targetH = static_cast<int>(cssHeight * dpr);
    if (targetW <= 0 || targetH <= 0) return;

    GLFWwindow* glfwWindow = window_.getGLFWwindow();
    int currentW = 0, currentH = 0;
    glfwGetFramebufferSize(glfwWindow, &currentW, &currentH);
    if (currentW == targetW && currentH == targetH) return;

    // Three writes for three different bits of state — none of them is enough
    // on its own:
    //   1) glfwSetWindowSize    — updates GLFW's internal width/height so
    //      future glfwGetFramebufferSize calls return the live size (used by
    //      renderMenuFrame / tick to set viewport and aspect ratio).
    //   2) emscripten_set_canvas_element_size — resizes the actual WebGL
    //      drawing buffer; without this the JS canvas.width/height keeps the
    //      value the GLFW port stamped on it at glfwCreateWindow time.
    //   3) framebufferSizeCallback — runs the same path a desktop resize
    //      would take: glViewport + sceneFbo / bloom FBO resizes.
    glfwSetWindowSize(glfwWindow, targetW, targetH);
    emscripten_set_canvas_element_size("#canvas", targetW, targetH);
    framebufferSizeCallback(glfwWindow, targetW, targetH);
}

//----------------------------------------------------------------------------
// Touch input (Emscripten only)
//----------------------------------------------------------------------------

namespace
{
    constexpr float  kTouchPinchSensitivity = 0.02f;   ///< pixels-per-frame → keyboard deltaTime
    constexpr float  kTouchPinchDeadZonePx  = 1.0f;    ///< below this, ignore pinch jitter
}

bool Application::touchStartCallback(int, const EmscriptenTouchEvent* e, void* userData)
{
    if (e && userData) static_cast<Application*>(userData)->handleTouchStart(*e);
    return false;
}
bool Application::touchMoveCallback(int, const EmscriptenTouchEvent* e, void* userData)
{
    if (e && userData) static_cast<Application*>(userData)->handleTouchMove(*e);
    return false;
}
bool Application::touchEndCallback(int, const EmscriptenTouchEvent* e, void* userData)
{
    if (e && userData) static_cast<Application*>(userData)->handleTouchEnd(*e);
    return false;
}
bool Application::touchCancelCallback(int, const EmscriptenTouchEvent* e, void* userData)
{
    if (e && userData) static_cast<Application*>(userData)->handleTouchCancel(*e);
    return false;
}

void Application::handleTouchStart(const EmscriptenTouchEvent& e)
{
    for (int i = 0; i < e.numTouches; ++i)
    {
        const EmscriptenTouchPoint& tp = e.touches[i];
        if (!tp.isChanged) continue;

        // Skip if we already track this id (defensive — touchstart shouldn't
        // re-report an existing finger, but browsers occasionally do).
        bool tracked = false;
        for (const TouchPoint& slot : activeTouches_)
            if (slot.id == tp.identifier) { tracked = true; break; }
        if (tracked) continue;

        for (TouchPoint& slot : activeTouches_)
        {
            if (slot.id == -1)
            {
                slot.id            = tp.identifier;
                slot.startX        = static_cast<float>(tp.targetX);
                slot.startY        = static_cast<float>(tp.targetY);
                slot.lastX         = slot.startX;
                slot.lastY         = slot.startY;
                slot.maxMovementPx = 0.0f;
                slot.startTimeMs   = e.timestamp;
                break;
            }
        }
    }

    // Initialize pinch baseline whenever the count reaches 2.
    int activeCount = 0;
    for (const TouchPoint& s : activeTouches_) if (s.id != -1) ++activeCount;
    if (activeCount == 2)
    {
        const float dx = activeTouches_[0].lastX - activeTouches_[1].lastX;
        const float dy = activeTouches_[0].lastY - activeTouches_[1].lastY;
        lastPinchDistance_ = std::sqrt(dx*dx + dy*dy);
    }
    else
    {
        lastPinchDistance_ = 0.0f;
    }
}

void Application::handleTouchMove(const EmscriptenTouchEvent& e)
{
    // Update tracked touches and gather per-slot deltas. Compute deltas BEFORE
    // overwriting lastX/Y so the camera math has correct per-event values.
    float dx[2] = {0.0f, 0.0f};
    float dy[2] = {0.0f, 0.0f};
    bool  moved[2] = {false, false};

    for (int i = 0; i < e.numTouches; ++i)
    {
        const EmscriptenTouchPoint& tp = e.touches[i];
        for (size_t s = 0; s < activeTouches_.size(); ++s)
        {
            TouchPoint& slot = activeTouches_[s];
            if (slot.id != tp.identifier) continue;

            const float newX = static_cast<float>(tp.targetX);
            const float newY = static_cast<float>(tp.targetY);
            dx[s]    = newX - slot.lastX;
            dy[s]    = newY - slot.lastY;
            moved[s] = true;

            const float fromStartX = newX - slot.startX;
            const float fromStartY = newY - slot.startY;
            const float total      = std::sqrt(fromStartX*fromStartX + fromStartY*fromStartY);
            if (total > slot.maxMovementPx) slot.maxMovementPx = total;

            slot.lastX = newX;
            slot.lastY = newY;
            break;
        }
    }

    // While ImGui is dragging a widget (slider, popup), let synthetic mouse
    // events drive the UI; don't fight it from C++.
    if (ImGui::GetIO().WantCaptureMouse) return;

    int activeCount = 0;
    int firstSlot   = -1;
    for (size_t s = 0; s < activeTouches_.size(); ++s)
    {
        if (activeTouches_[s].id != -1)
        {
            ++activeCount;
            if (firstSlot == -1) firstSlot = static_cast<int>(s);
        }
    }

    if (activeCount == 1 && firstSlot >= 0 && moved[firstSlot])
    {
        // 1-finger drag → camera rotation. processMouseMovement convention:
        // xOffset = newX - lastX, yOffset = lastY - newY  (Y is flipped).
        camera_.processMouseMovement(dx[firstSlot], -dy[firstSlot]);
    }
    else if (activeCount == 2)
    {
        // 2-finger pinch → zoom (mirrors scrollCallback, which translates
        // wheel into KEY_W / KEY_S press).
        const float ddx = activeTouches_[0].lastX - activeTouches_[1].lastX;
        const float ddy = activeTouches_[0].lastY - activeTouches_[1].lastY;
        const float distance = std::sqrt(ddx*ddx + ddy*ddy);

        if (lastPinchDistance_ > 0.0f)
        {
            const float pinchDelta = distance - lastPinchDistance_;
            if (std::abs(pinchDelta) > kTouchPinchDeadZonePx)
            {
                camera_.processKeyboard(pinchDelta > 0 ? GLFW_KEY_W : GLFW_KEY_S,
                                        std::abs(pinchDelta) * kTouchPinchSensitivity);
            }
        }
        lastPinchDistance_ = distance;
    }
}

void Application::handleTouchEnd(const EmscriptenTouchEvent& e)
{
    for (int i = 0; i < e.numTouches; ++i)
    {
        const EmscriptenTouchPoint& tp = e.touches[i];
        if (!tp.isChanged) continue;
        for (TouchPoint& slot : activeTouches_)
        {
            if (slot.id == tp.identifier) { slot.id = -1; break; }
        }
    }
    int activeCount = 0;
    for (const TouchPoint& s : activeTouches_) if (s.id != -1) ++activeCount;
    if (activeCount < 2) lastPinchDistance_ = 0.0f;
}

void Application::handleTouchCancel(const EmscriptenTouchEvent& e)
{
    handleTouchEnd(e);
}
#endif

void Application::rebuildSceneFbo()
{
    const int samples = uiManager_.msaaEnabled ? kSceneMsaaSamples : 1;
    sceneFbo_.setSamples(samples);
}

void Application::run()
{
    // Mount IDBFS and pull existing saves out of IndexedDB before the main
    // loop starts. On desktop this is a no-op that returns true. On web,
    // failure means private browsing or an unsupported browser — we still
    // run, but warn the user that anything they save will vanish on reload.
    if (!web::initPersistence())
    {
        persistenceWarningPending_ = true;
    }

#ifdef SOLARSYSTEM_BUILD_WEB
    // Browsers don't tolerate blocking main loops — surrender control
    // to requestAnimationFrame via Emscripten. fps=0 means "use rAF";
    // simulate_infinite_loop=1 unwinds the C++ stack so destructors
    // for stack objects past run() never fire (acceptable here since
    // Application::~Application releases everything we own).
    emscripten_set_main_loop_arg(&Application::emscriptenTick, this, /*fps=*/0,
                                 /*simulate_infinite_loop=*/1);
#else
    while (!glfwWindowShouldClose(window_.getGLFWwindow()))
    {
        tick();
    }
#endif
}

//----------------------------------------------------------------------------
// Frame loop
//----------------------------------------------------------------------------

void Application::tick()
{
#ifdef SOLARSYSTEM_BUILD_WEB
    // The browser owns the canvas dimensions — keep GLFW + FBOs in sync
    // before any rendering decisions for this frame.
    syncWebCanvasSize();
#endif

    if (persistenceWarningPending_)
    {
        uiManager_.toasts().warning("Browser persistence unavailable — saves will be lost on reload.");
        persistenceWarningPending_ = false;
    }

    if (uiManager_.msaaDirty)
    {
        rebuildSceneFbo();
        uiManager_.msaaDirty = false;
        uiManager_.toasts().info(uiManager_.msaaEnabled ? "MSAA enabled" : "MSAA disabled");
    }

    const float currentFrameTime = static_cast<float>(glfwGetTime());
    const float deltaTime        = currentFrameTime - previousFrameTime_;
    previousFrameTime_ = currentFrameTime;

    if (appState_ == AppState::Menu)
    {
        renderMenuFrame(deltaTime);
        return;
    }

    GLFWwindow* glfwWindow = window_.getGLFWwindow();
    if (glfwGetKey(glfwWindow, GLFW_KEY_W) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_W, deltaTime);
    if (glfwGetKey(glfwWindow, GLFW_KEY_S) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_S, deltaTime);
    if (glfwGetKey(glfwWindow, GLFW_KEY_A) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_A, deltaTime);
    if (glfwGetKey(glfwWindow, GLFW_KEY_D) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_D, deltaTime);

    handleHotkeys();

    // Advance the simulation FIRST, then snap the orbital camera onto the
    // freshly integrated body position. Doing this in the reverse order
    // left the camera reading the previous-frame target while bodies
    // rendered at their new positions — fast inner planets visibly
    // "teleported" relative to the orbital camera every frame.
    physics_.update(bodies_, static_cast<double>(deltaTime));
    sampleOrbitTrails();
    refreshOrbitalCameraTarget();
    camera_.update(deltaTime);

    // Refresh the path prediction (throttled) so the dashed line stays in
    // sync with the live simulation without paying its O(N² × samples)
    // cost on every frame.
    const int  predSelected = uiManager_.getSelectedPlanetIndex();
    const bool predValid    = uiManager_.showPathPrediction
                              && predSelected >= 0
                              && predSelected < static_cast<int>(bodies_.size());
    if (predValid)
    {
        // Freeze the horizon on enable / selection change. Recomputing it
        // every refresh let the tip oscillate (estimateOrbitalPeriod uses
        // the instantaneous r, which breathes in elliptical orbits).
        if (lastPredictionSelected_ != predSelected || predictionHorizonSeconds_ <= 0.0)
        {
            predictionHorizonSeconds_  = PathPredictor::estimateOrbitalPeriod(bodies_, predSelected);
            lastPredictionSelected_    = predSelected;
            framesSinceLastPrediction_ = kPredictionRefreshFrames;  // force immediate refresh
        }

        if (framesSinceLastPrediction_ >= kPredictionRefreshFrames)
        {
            pathPredictor_.recompute(bodies_, predSelected,
                                     predictionHorizonSeconds_, kPredictionSampleCount);
            framesSinceLastPrediction_ = 0;
        }
        else
        {
            ++framesSinceLastPrediction_;
        }
    }
    else
    {
        pathPredictor_.clear();
        predictionHorizonSeconds_  = 0.0;
        lastPredictionSelected_    = -1;
        framesSinceLastPrediction_ = kPredictionRefreshFrames;  // force refresh on re-enable
    }

    int framebufferWidth = 0, framebufferHeight = 0;
    glfwGetFramebufferSize(glfwWindow, &framebufferWidth, &framebufferHeight);
    const float aspectRatio = static_cast<float>(framebufferWidth)
                            / static_cast<float>(std::max(framebufferHeight, 1));

    // Demo mode overrides the view with a slow auto-orbit around the
    // system origin and ignores the camera state. Otherwise normal.
    glm::mat4 view;
    if (uiManager_.demoModeActive)
    {
        demoTime_ += deltaTime;
        const float orbitAngle  = demoTime_ * 0.08f;
        float       maxBody     = 100.0f;
        for (const auto& b : bodies_) {
            const float r = glm::length(b.renderPosition());
            if (r > maxBody) maxBody = r;
        }
        const float radius = std::min(maxBody, 2000.0f) * 1.6f;
        const glm::vec3 demoCameraPos(radius * std::cos(orbitAngle),
                                      radius * 0.45f,
                                      radius * std::sin(orbitAngle));
        view = glm::lookAt(demoCameraPos, glm::vec3(0.0f), glm::vec3(0.0f, 1.0f, 0.0f));
    }
    else
    {
        view = camera_.getViewMatrix();
    }

    const glm::mat4 projection = glm::perspective(glm::radians(fieldOfView_),
                                                  aspectRatio,
                                                  kProjectionNearPlane,
                                                  kProjectionFarPlane);

    // ---- Scene pass: render the full 3D world into sceneFbo_ -----------
    sceneFbo_.bind();
    glViewport(0, 0, sceneFbo_.width(), sceneFbo_.height());
    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    renderSky(view, projection);
    renderBodies(view, projection);
    renderGrid(view, projection);
    // Atmospheres before rings so the visible ring isn't hazed over by
    // its own planet's atmosphere shell.
    renderAtmospheres(view, projection);
    renderRings(view, projection);

    if (uiManager_.showTrails)         renderTrails(view, projection);
    if (uiManager_.showPathPrediction) renderPathPrediction(view, projection);
    if (uiManager_.showLagrange)       renderLagrange(view, projection);
    if (uiManager_.isPlacingBody())    renderPlacementHint(view, projection);

    // ---- MSAA resolve: blit the multisample sceneFbo_ into a single-sample
    //      texture (sceneResolveFbo_) so the composite pass can sample from it.
    sceneFbo_.blitColorTo(sceneResolveFbo_);

    // ---- Bloom passes: bright-pass emissive bodies, then ping-pong blur -
    GLuint blurredBloomTexture = 0;
    if (uiManager_.showBloom)
    {
        renderBloomPasses(view, projection, blurredBloomTexture);
    }
    else
    {
        bloomPingFbo_.bind();
        glViewport(0, 0, bloomPingFbo_.width(), bloomPingFbo_.height());
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        blurredBloomTexture = bloomPingFbo_.colorTexture();
    }

    // ---- Composite: scene + bloom into the default framebuffer ---------
    renderComposite(blurredBloomTexture, framebufferWidth, framebufferHeight);

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    // Apply mobile vs desktop ImGui style once per frame, immediately after
    // NewFrame so ImGui's DisplaySize reflects the current viewport (set by
    // ImGui_ImplGlfw_NewFrame above). Idempotent; cached so per-frame cost
    // is one int comparison after the first breakpoint flip.
    ui::applyResponsiveStyle();

    // Demo Mode hides every panel and modal except the tutorial — that
    // way Esc / F11 can exit, but no chrome distracts from the cinematic.
    if (!uiManager_.demoModeActive)
    {
        uiManager_.render(window_, camera_, deltaTime, bodies_, grid_, physics_, gridSettings_);

        if (uiManager_.menuRequested)
        {
            openReturnToMenuPopup_ = true;
            uiManager_.menuRequested = false;
        }
        if (uiManager_.settingsRequested)
        {
            settingsModal_.requestOpen();
            uiManager_.settingsRequested = false;
        }
        if (uiManager_.saveRequested)
        {
            saveLoadModal_.requestOpenSave();
            uiManager_.saveRequested = false;
        }
        if (uiManager_.loadRequested)
        {
            saveLoadModal_.requestOpenLoad();
            uiManager_.loadRequested = false;
        }
        if (uiManager_.addPlanetRequested)
        {
            addPlanetModal_.requestOpen();
            uiManager_.addPlanetRequested = false;
        }
        if (uiManager_.helpRequested)
        {
            tutorial_.requestOpen();
            uiManager_.helpRequested = false;
        }
        if (uiManager_.viewPresetRequested >= 0)
        {
            applyViewPreset(static_cast<ViewPreset>(uiManager_.viewPresetRequested));
            uiManager_.viewPresetRequested = -1;
        }

        settingsModal_.render(camera_, fieldOfView_, guiScale_, uiManager_, gridSettings_);
        saveLoadModal_.render(bodies_, physics_, camera_, uiManager_);
        addPlanetModal_.render(bodies_, uiManager_);
        renderConfirmModals();
    }

    tutorial_.render();

    if (uiManager_.vsyncDirty)
    {
        glfwSwapInterval(uiManager_.vsync ? 1 : 0);
        uiManager_.vsyncDirty = false;
    }

    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    glfwSwapBuffers(glfwWindow);
    glfwPollEvents();
}

//----------------------------------------------------------------------------
// Menu state
//----------------------------------------------------------------------------

void Application::renderMenuFrame(float deltaTime)
{
    menuTime_ += deltaTime;

    GLFWwindow* glfwWindow = window_.getGLFWwindow();

    int framebufferWidth = 0, framebufferHeight = 0;
    glfwGetFramebufferSize(glfwWindow, &framebufferWidth, &framebufferHeight);
    const float aspectRatio = static_cast<float>(framebufferWidth)
                            / static_cast<float>(std::max(framebufferHeight, 1));

    // Slow camera orbit around the origin for a cinematic skybox.
    constexpr float kMenuOrbitRadius      = 300.0f;
    constexpr float kMenuOrbitHeight      = 60.0f;
    constexpr float kMenuOrbitAngularRate = 0.05f;
    const float angle = menuTime_ * kMenuOrbitAngularRate;
    const glm::vec3 menuCameraPosition(kMenuOrbitRadius * std::cos(angle),
                                       kMenuOrbitHeight,
                                       kMenuOrbitRadius * std::sin(angle));

    const glm::mat4 view       = glm::lookAt(menuCameraPosition,
                                             glm::vec3(0.0f),
                                             glm::vec3(0.0f, 1.0f, 0.0f));
    const glm::mat4 projection = glm::perspective(glm::radians(fieldOfView_),
                                                  aspectRatio,
                                                  kProjectionNearPlane,
                                                  kProjectionFarPlane);

    // The menu draws directly to the default framebuffer — no offscreen FBO
    // bounce, no bloom. Bind explicitly so we never inherit a stale binding.
    Framebuffer::bindDefault();
    glViewport(0, 0, framebufferWidth, framebufferHeight);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    renderSky(view, projection);

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    ui::applyResponsiveStyle();

    const StartMenuAction action = startMenu_.render(framebufferWidth, framebufferHeight);

    if (action == StartMenuAction::Settings)
    {
        settingsModal_.requestOpen();
    }

    // Settings is the only modal we render from the menu — it doesn't depend
    // on the simulation state, only on settings_ + camera_ + uiManager_.
    settingsModal_.render(camera_, fieldOfView_, guiScale_, uiManager_, gridSettings_);

    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    glfwSwapBuffers(glfwWindow);
    glfwPollEvents();

    switch (action)
    {
        case StartMenuAction::Start:    startSimulation(); break;
        case StartMenuAction::Quit:     glfwSetWindowShouldClose(glfwWindow, true); break;
        case StartMenuAction::Load:     /* Not yet wired from the menu. */ break;
        case StartMenuAction::Settings: /* Handled above. */                break;
        case StartMenuAction::None:     break;
    }
}

void Application::startSimulation()
{
    bodies_.clear();
    loadDefaultBodies();
    shiftToBarycenterFrame();
    camera_.reset();
    physics_.reset();
    pathPredictor_.clear();
    framesSinceLastPrediction_ = kPredictionRefreshFrames;
    appState_ = AppState::Running;
    previousFrameTime_ = static_cast<float>(glfwGetTime());

    // Auto-open the tutorial on the very first launch (no `.tutorial_seen`
    // marker yet). Subsequent launches can still re-open it via the "?"
    // button in the top actionbar.
    if (Tutorial::isFirstRun())
    {
        tutorial_.requestOpen();
    }
}

void Application::returnToMenu()
{
    bodies_.clear();
    uiManager_.clearSelection();
    camera_.reset();
    physics_.reset();
    pathPredictor_.clear();
    appState_ = AppState::Menu;
    menuTime_ = 0.0f;
    previousFrameTime_ = static_cast<float>(glfwGetTime());
}

void Application::captureScreenshot()
{
    int framebufferWidth = 0, framebufferHeight = 0;
    glfwGetFramebufferSize(window_.getGLFWwindow(), &framebufferWidth, &framebufferHeight);

    const auto now      = std::chrono::system_clock::now();
    const auto wallTime = std::chrono::system_clock::to_time_t(now);
    std::tm    localTime{};
#ifdef _WIN32
    localtime_s(&localTime, &wallTime);
#else
    localtime_r(&wallTime, &localTime);
#endif
    char timestamp[32];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%d_%H-%M-%S", &localTime);
    const std::string filename = std::string("solarsystem_") + timestamp + ".bmp";

#ifdef SOLARSYSTEM_BUILD_WEB
    // Web: encode the framebuffer in memory and hand it to the browser as a
    // Blob download. Writing to the virtual FS would lose the file on reload.
    const std::string bytes = encodeFramebufferAsBMP(framebufferWidth, framebufferHeight);
    if (bytes.empty())
    {
        uiManager_.toasts().error("Screenshot failed: cannot read framebuffer");
        return;
    }
    web::downloadBlob(filename, bytes);
    uiManager_.toasts().success("Screenshot downloading: " + filename);
#else
    namespace fs = std::filesystem;
    const fs::path directory("screenshots");
    std::error_code errorCode;
    fs::create_directories(directory, errorCode);
    const std::string fullPath = (directory / filename).string();

    if (captureFramebufferToBMP(fullPath, framebufferWidth, framebufferHeight))
    {
        uiManager_.toasts().success("Screenshot saved: " + fullPath);
    }
    else
    {
        uiManager_.toasts().error("Screenshot failed: cannot write " + fullPath);
    }
#endif
}

void Application::saveBookmark(int slot)
{
    if (slot < 0 || slot >= static_cast<int>(bookmarks_.size())) return;
    bookmarks_[slot].position = camera_.getPosition();
    bookmarks_[slot].yaw      = camera_.getYaw();
    bookmarks_[slot].pitch    = camera_.getPitch();
    bookmarks_[slot].occupied = true;
    uiManager_.toasts().success("Bookmark " + std::to_string(slot + 1) + " saved");
}

void Application::restoreBookmark(int slot)
{
    if (slot < 0 || slot >= static_cast<int>(bookmarks_.size())) return;
    const auto& bm = bookmarks_[slot];
    if (!bm.occupied)
    {
        uiManager_.toasts().info("Bookmark " + std::to_string(slot + 1) + " empty (Shift+F"
                                 + std::to_string(slot + 5) + " to save)");
        return;
    }
    camera_.flyToPose(bm.position, bm.yaw, bm.pitch);
}

void Application::applyViewPreset(ViewPreset preset)
{
    // Auto-fit: distance scales with the furthest body, clamped so a
    // Trappist-1 sized system doesn't snap the camera right next to the
    // star and Solar System doesn't pull the camera 30 AU out.
    float maxBodyDistance = 100.0f;
    for (const auto& body : bodies_)
    {
        const float r = glm::length(body.renderPosition());
        if (r > maxBodyDistance) maxBodyDistance = r;
    }
    maxBodyDistance       = std::min(maxBodyDistance, 2000.0f);
    const float distance  = maxBodyDistance * 1.5f;

    glm::vec3 position;
    float     yaw   = -90.0f;
    float     pitch = 0.0f;
    switch (preset)
    {
        case ViewPreset::TopDown:
            position = glm::vec3(0.0f, distance, 0.0f);
            yaw      = -90.0f;
            pitch    = -89.0f;   // shader clamps at ±89; effectively straight down
            break;
        case ViewPreset::SideOn:
            position = glm::vec3(distance, 0.0f, 0.0f);
            yaw      = 180.0f;
            pitch    = 0.0f;
            break;
        case ViewPreset::Default:
        default:
            position = kInitialCameraPosition;
            yaw      = kInitialCameraYaw;
            pitch    = kInitialCameraPitch;
            break;
    }
    camera_.flyToPose(position, yaw, pitch);
}

void Application::renderConfirmModals()
{
    constexpr const char* kReturnPopupId = "Return to Menu?";
    constexpr const char* kQuitPopupId   = "Quit Application?";

    if (openReturnToMenuPopup_)
    {
        ImGui::OpenPopup(kReturnPopupId);
        openReturnToMenuPopup_ = false;
    }
    if (openQuitPopup_)
    {
        ImGui::OpenPopup(kQuitPopupId);
        openQuitPopup_ = false;
    }

    const ImVec2 viewportCenter = ImGui::GetMainViewport()->GetCenter();
    constexpr ImVec2 kButtonSize(120.0f, 0.0f);

    ImGui::SetNextWindowPos(viewportCenter, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    if (ImGui::BeginPopupModal(kReturnPopupId, nullptr, ImGuiWindowFlags_AlwaysAutoResize))
    {
        ImGui::TextUnformatted("Discard the current simulation and return to the main menu?");
        ImGui::Spacing();
        if (ImGui::Button("Yes", kButtonSize))
        {
            returnToMenu();
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button("No", kButtonSize))
        {
            ImGui::CloseCurrentPopup();
        }
        ImGui::EndPopup();
    }

    ImGui::SetNextWindowPos(viewportCenter, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    if (ImGui::BeginPopupModal(kQuitPopupId, nullptr, ImGuiWindowFlags_AlwaysAutoResize))
    {
        ImGui::TextUnformatted("Quit SolarSystemGL?");
        ImGui::Spacing();
        if (ImGui::Button("Quit", kButtonSize))
        {
            glfwSetWindowShouldClose(window_.getGLFWwindow(), GLFW_TRUE);
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button("Cancel", kButtonSize))
        {
            ImGui::CloseCurrentPopup();
        }
        ImGui::EndPopup();
    }
}

//----------------------------------------------------------------------------
// Initialization helpers
//----------------------------------------------------------------------------

void Application::loadDefaultBodies()
{
    struct DefaultBody
    {
        const char* name;
        double      semiMajorAxisAU;
        double      orbitalVelocityMS;
        double      massKg;
        float       densityKgPerM3;
        glm::vec3   color;
        float       emissive;
        float       displayScale;
        bool        hasRings;
        bool        hasAtmosphere;
        float       atmosphereHeight;
        glm::vec3   atmosphereColor;
        float       atmosphereDensity;
    };

    // Atmosphere tints are Rayleigh-flavored approximations of each planet's
    // sky color as imaged from orbit (or its disk color for gas giants).
    const DefaultBody defaults[] = {
        // name      AU       v(m/s)    mass(kg)   density   color                                  emi  scale  rings  atm    height  atmColor                                  atmDensity
        { "Sun",     0.000,      0.0,   1.989e30,  1408.0f,  glm::vec3(1.00f, 0.90f, 0.30f),       1.0f, 0.4f,  false, false, 0.00f,  glm::vec3(0.0f),                          0.0f },
        { "Mercury", 0.387,  47900.0,   3.3011e23, 5427.0f,  glm::vec3(0.50f, 0.50f, 0.50f),       0.0f, 1.0f,  false, false, 0.00f,  glm::vec3(0.0f),                          0.0f },
        { "Venus",   0.723,  35000.0,   4.8675e24, 5243.0f,  glm::vec3(0.95f, 0.85f, 0.55f),       0.0f, 1.0f,  false, true,  0.08f,  glm::vec3(1.00f, 0.85f, 0.40f),           1.5f },
        { "Earth",   1.000,  29780.0,   5.9720e24, 5514.0f,  glm::vec3(0.20f, 0.40f, 1.00f),       0.0f, 1.0f,  false, true,  0.05f,  glm::vec3(0.40f, 0.60f, 1.00f),           1.0f },
        { "Mars",    1.524,  24100.0,   6.4171e23, 3933.0f,  glm::vec3(0.80f, 0.30f, 0.10f),       0.0f, 1.0f,  false, true,  0.03f,  glm::vec3(0.95f, 0.50f, 0.35f),           0.5f },
        { "Jupiter", 5.203,  13070.0,   1.8980e27, 1326.0f,  glm::vec3(0.90f, 0.70f, 0.40f),       0.0f, 1.0f,  false, true,  0.08f,  glm::vec3(0.95f, 0.78f, 0.50f),           1.4f },
        { "Saturn",  9.537,   9680.0,   5.6834e26,  687.0f,  glm::vec3(0.95f, 0.85f, 0.50f),       0.0f, 1.0f,  true,  true,  0.07f,  glm::vec3(0.95f, 0.85f, 0.60f),           1.2f },
        { "Uranus", 19.191,   6800.0,   8.6810e25, 1271.0f,  glm::vec3(0.60f, 0.85f, 0.90f),       0.0f, 1.0f,  false, true,  0.06f,  glm::vec3(0.45f, 0.85f, 0.90f),           1.1f },
        { "Neptune",30.070,   5430.0,   1.0240e26, 1638.0f,  glm::vec3(0.30f, 0.40f, 0.85f),       0.0f, 1.0f,  false, true,  0.07f,  glm::vec3(0.25f, 0.40f, 0.95f),           1.2f },
    };

    for (const auto& spec : defaults)
    {
        CelestialBody body;
        body.pos_m             = glm::dvec3(spec.semiMajorAxisAU * AU, 0.0, 0.0);
        body.vel_m             = glm::dvec3(0.0, 0.0, spec.orbitalVelocityMS);
        body.mass_kg           = spec.massKg;
        body.name              = spec.name;
        body.color             = spec.color;
        body.density           = spec.densityKgPerM3;
        body.emissive          = spec.emissive;
        body.displayScale      = spec.displayScale;
        body.hasRings          = spec.hasRings;
        body.hasAtmosphere     = spec.hasAtmosphere;
        body.atmosphereHeight  = spec.atmosphereHeight;
        body.atmosphereColor   = spec.atmosphereColor;
        body.atmosphereDensity = spec.atmosphereDensity;
        body.recalculateGeometry();
        bodies_.push_back(std::move(body));
    }
}

void Application::shiftToBarycenterFrame()
{
    glm::dvec3 totalMomentum(0.0);
    double     totalMass = 0.0;
    for (const auto& body : bodies_)
    {
        totalMomentum += body.vel_m * body.mass_kg;
        totalMass     += body.mass_kg;
    }
    if (totalMass <= 0.0) return;

    const glm::dvec3 centerOfMassVelocity = totalMomentum / totalMass;
    for (auto& body : bodies_)
    {
        body.vel_m -= centerOfMassVelocity;
    }
}

void Application::createAuxiliaryBuffers()
{
    // Dynamic VBO for trail line strips (re-uploaded per body per frame).
    glGenVertexArrays(1, &trailVAO_);
    glGenBuffers(1, &trailVBO_);
    glBindVertexArray(trailVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, trailVBO_);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(glm::vec3), nullptr);
    glEnableVertexAttribArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindVertexArray(0);

    // Static fullscreen unit quad — shared by the sky pass and every
    // fullscreen-quad bloom pass (bright-pass / blur / composite).
    const float fullscreenQuadVertices[] = {
        -1.0f, -1.0f,
         1.0f, -1.0f,
        -1.0f,  1.0f,
         1.0f,  1.0f,
    };
    glGenVertexArrays(1, &fullscreenQuadVAO_);
    glGenBuffers(1, &fullscreenQuadVBO_);
    glBindVertexArray(fullscreenQuadVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, fullscreenQuadVBO_);
    glBufferData(GL_ARRAY_BUFFER, sizeof(fullscreenQuadVertices), fullscreenQuadVertices, GL_STATIC_DRAW);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(float), nullptr);
    glEnableVertexAttribArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindVertexArray(0);

    // Ring mesh: triangle strip on the XZ plane, inner radius 1.0, outer 1.5.
    std::vector<glm::vec3> ringVertices;
    ringVertices.reserve(static_cast<size_t>(2 * (kRingSegmentCount + 1)));
    for (int segment = 0; segment <= kRingSegmentCount; ++segment)
    {
        const float angle = 2.0f * 3.14159265358979f
                          * static_cast<float>(segment)
                          / static_cast<float>(kRingSegmentCount);
        const float cosA  = std::cos(angle);
        const float sinA  = std::sin(angle);
        ringVertices.emplace_back(cosA * kRingInnerRadius, 0.0f, sinA * kRingInnerRadius);
        ringVertices.emplace_back(cosA * kRingOuterRadius, 0.0f, sinA * kRingOuterRadius);
    }
    ringVertexCount_ = static_cast<GLsizei>(ringVertices.size());

    glGenVertexArrays(1, &ringVAO_);
    glGenBuffers(1, &ringVBO_);
    glBindVertexArray(ringVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, ringVBO_);
    glBufferData(GL_ARRAY_BUFFER,
                 ringVertices.size() * sizeof(glm::vec3),
                 ringVertices.data(), GL_STATIC_DRAW);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(glm::vec3), nullptr);
    glEnableVertexAttribArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindVertexArray(0);
}

void Application::destroyAuxiliaryBuffers()
{
    if (trailVAO_)          glDeleteVertexArrays(1, &trailVAO_);
    if (trailVBO_)          glDeleteBuffers(1, &trailVBO_);
    if (fullscreenQuadVAO_) glDeleteVertexArrays(1, &fullscreenQuadVAO_);
    if (fullscreenQuadVBO_) glDeleteBuffers(1, &fullscreenQuadVBO_);
    if (ringVAO_)           glDeleteVertexArrays(1, &ringVAO_);
    if (ringVBO_)           glDeleteBuffers(1, &ringVBO_);
    trailVAO_ = trailVBO_ = fullscreenQuadVAO_ = fullscreenQuadVBO_ = ringVAO_ = ringVBO_ = 0;
}

//----------------------------------------------------------------------------
// Per-frame helpers
//----------------------------------------------------------------------------

void Application::refreshOrbitalCameraTarget()
{
    const int targetIndex = camera_.getOrbitalTargetIndex();
    if (targetIndex < 0 || targetIndex >= static_cast<int>(bodies_.size())) return;
    camera_.setOrbitalTargetPos(bodies_[targetIndex].renderPosition());
}

void Application::handleHotkeys()
{
    GLFWwindow* glfwWindow = window_.getGLFWwindow();
    const bool keyboardCaptured = ImGui::GetIO().WantCaptureKeyboard;

    const bool spaceDown = glfwGetKey(glfwWindow, GLFW_KEY_SPACE)  == GLFW_PRESS;
    const bool rDown     = glfwGetKey(glfwWindow, GLFW_KEY_R)      == GLFW_PRESS;
    const bool fDown     = glfwGetKey(glfwWindow, GLFW_KEY_F)      == GLFW_PRESS;
    const bool escDown   = glfwGetKey(glfwWindow, GLFW_KEY_ESCAPE) == GLFW_PRESS;
    const bool oneDown   = glfwGetKey(glfwWindow, GLFW_KEY_1)      == GLFW_PRESS;
    const bool twoDown   = glfwGetKey(glfwWindow, GLFW_KEY_2)      == GLFW_PRESS;
    const bool f12Down   = glfwGetKey(glfwWindow, GLFW_KEY_F12)    == GLFW_PRESS;

    // F12 fires regardless of ImGui keyboard capture — screenshots should
    // be available at all times.
    if (f12Down && !wasF12Pressed_) captureScreenshot();
    wasF12Pressed_ = f12Down;

    // Mobile / overflow-menu equivalent of the F12 hotkey.
    if (uiManager_.screenshotRequested)
    {
        uiManager_.screenshotRequested = false;
        captureScreenshot();
    }

    // F1 / F2 / F3 — Blender-flavoured view presets. Always-on (no
    // keyboard-capture gate) so they work even with a dialog focused.
    const bool f1Down = glfwGetKey(glfwWindow, GLFW_KEY_F1) == GLFW_PRESS;
    const bool f2Down = glfwGetKey(glfwWindow, GLFW_KEY_F2) == GLFW_PRESS;
    const bool f3Down = glfwGetKey(glfwWindow, GLFW_KEY_F3) == GLFW_PRESS;
    if (f1Down && !wasF1Pressed_) applyViewPreset(ViewPreset::Default);
    if (f2Down && !wasF2Pressed_) applyViewPreset(ViewPreset::TopDown);
    if (f3Down && !wasF3Pressed_) applyViewPreset(ViewPreset::SideOn);
    wasF1Pressed_ = f1Down;
    wasF2Pressed_ = f2Down;
    wasF3Pressed_ = f3Down;

    // F11 — toggle Demo Mode (cinematic auto-orbit, UI hidden).
    const bool f11Down = glfwGetKey(glfwWindow, GLFW_KEY_F11) == GLFW_PRESS;
    if (f11Down && !wasF11Pressed_)
    {
        uiManager_.demoModeActive = !uiManager_.demoModeActive;
        if (uiManager_.demoModeActive) demoTime_ = 0.0f;
    }
    wasF11Pressed_ = f11Down;

    // F5..F8 — camera bookmarks. Plain key restores the slot; Shift + key
    // captures the current pose into it. These also fire regardless of
    // ImGui keyboard capture, since they don't conflict with any panel.
    const bool shiftHeld = glfwGetKey(glfwWindow, GLFW_KEY_LEFT_SHIFT)  == GLFW_PRESS
                        || glfwGetKey(glfwWindow, GLFW_KEY_RIGHT_SHIFT) == GLFW_PRESS;
    for (int slot = 0; slot < 4; ++slot)
    {
        const int  glfwKey = GLFW_KEY_F5 + slot;
        const bool down    = glfwGetKey(glfwWindow, glfwKey) == GLFW_PRESS;
        if (down && !wasBookmarkKeyPressed_[slot])
        {
            if (shiftHeld) saveBookmark(slot);
            else           restoreBookmark(slot);
        }
        wasBookmarkKeyPressed_[slot] = down;
    }

    if (!keyboardCaptured)
    {
        if (spaceDown && !wasSpacePressed_) physics_.paused = !physics_.paused;
        if (rDown     && !wasRPressed_)     camera_.reset();

        if (fDown && !wasFPressed_)
        {
            const int selected = uiManager_.getSelectedPlanetIndex();
            if (selected >= 0 && selected < static_cast<int>(bodies_.size()))
            {
                camera_.startSmoothMove(bodies_[selected].renderPosition(),
                                        bodies_[selected].focusDistance());
            }
        }

        if (escDown && !wasEscPressed_)
        {
            // Triple-stage Esc:
            //   1. In Demo Mode → exit Demo Mode.
            //   2. With a body selected → clear the selection (hide Planet Info).
            //   3. Otherwise → prompt Return-to-Menu.
            if (uiManager_.demoModeActive)
            {
                uiManager_.demoModeActive = false;
            }
            else if (uiManager_.getSelectedPlanetIndex() >= 0)
            {
                uiManager_.clearSelection();
            }
            else
            {
                openReturnToMenuPopup_ = true;
            }
        }

        if (oneDown && !wasOnePressed_) camera_.setMode(CameraMode::FREE);
        if (twoDown && !wasTwoPressed_)
        {
            const int selected = uiManager_.getSelectedPlanetIndex();
            if (selected >= 0 && selected < static_cast<int>(bodies_.size()))
            {
                camera_.flyToOrbital(selected,
                                     bodies_[selected].renderPosition(),
                                     bodies_[selected].focusDistance());
            }
        }
    }

    wasSpacePressed_ = spaceDown;
    wasRPressed_     = rDown;
    wasFPressed_     = fDown;
    wasEscPressed_   = escDown;
    wasOnePressed_   = oneDown;
    wasTwoPressed_   = twoDown;
}

void Application::sampleOrbitTrails()
{
    for (auto& body : bodies_)
    {
        const glm::vec3 currentPosition = body.renderPosition();

        if (!body.trailPoints.empty())
        {
            const float jump = glm::distance(body.trailPoints.back(), currentPosition);
            if (jump > kTrailTeleportJumpWU) body.trailPoints.clear();
        }

        const bool firstSample = body.trailPoints.empty();
        const bool movedEnough = !firstSample
            && glm::distance(body.trailPoints.back(), currentPosition) > kMinimumTrailStepWU;

        if (firstSample || movedEnough)
        {
            body.trailPoints.push_back(currentPosition);
            if (body.trailPoints.size() > kTrailHistoryCapacity)
            {
                body.trailPoints.pop_front();
            }
        }
    }
}

//----------------------------------------------------------------------------
// Render passes
//----------------------------------------------------------------------------

void Application::renderSky(const glm::mat4& view, const glm::mat4& projection)
{
    skyShader_.use();
    skyShader_.setMat4("invView", glm::inverse(view));
    skyShader_.setMat4("invProj", glm::inverse(projection));
    glDisable(GL_DEPTH_TEST);
    glBindVertexArray(fullscreenQuadVAO_);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    glEnable(GL_DEPTH_TEST);
}

void Application::renderBodies(const glm::mat4& view, const glm::mat4& projection)
{
    const glm::vec3 lightPosition = bodies_.empty()
        ? glm::vec3(0.0f)
        : bodies_[0].renderPosition();

    bodyShader_.use();
    bodyShader_.setMat4("view",       view);
    bodyShader_.setMat4("projection", projection);
    bodyShader_.setMat4("model",      glm::mat4(1.0f));
    bodyShader_.setVec3("lightPos",   lightPosition);
    bodyShader_.setVec3("viewPos",    camera_.getPosition());

    for (const auto& body : bodies_)
    {
        // Ring-shadow uniforms are body-specific: ringed bodies cast a
        // shadow on their own surface; everyone else has no shadow.
        if (body.hasRings)
        {
            const float displayRadius = body.radius * body.displayScale;
            const float ringScale     = displayRadius * kRingScaleMultiplier;
            bodyShader_.setInt  ("hasRingShadow",   1);
            bodyShader_.setVec3 ("ringCenter",      body.renderPosition());
            bodyShader_.setFloat("ringInnerRadius", ringScale * kRingInnerRadius);
            bodyShader_.setFloat("ringOuterRadius", ringScale * kRingOuterRadius);
        }
        else
        {
            bodyShader_.setInt("hasRingShadow", 0);
        }
        body.render(bodyShader_);
    }
}

void Application::renderGrid(const glm::mat4& view, const glm::mat4& projection)
{
    if (!gridSettings_.visible) return;

    gridShader_.use();
    gridShader_.setMat4("view",       view);
    gridShader_.setMat4("projection", projection);
    gridShader_.setMat4("model",      glm::mat4(1.0f));
    gridShader_.setVec3("cameraPos",  camera_.getPosition());
    grid_.draw(gridShader_, bodies_, gridSettings_);
}

void Application::renderRings(const glm::mat4& view, const glm::mat4& projection)
{
    const glm::vec3 lightPosition = bodies_.empty()
        ? glm::vec3(0.0f)
        : bodies_[0].renderPosition();

    ringShader_.use();
    ringShader_.setMat4("view",       view);
    ringShader_.setMat4("projection", projection);
    ringShader_.setVec3("ringColor",  kSaturnRingColor);
    ringShader_.setVec3("lightPos",   lightPosition);

    glBindVertexArray(ringVAO_);
    glDepthMask(GL_FALSE);
    for (const auto& body : bodies_)
    {
        if (!body.hasRings) continue;
        const float displayRadius = body.radius * body.displayScale;
        const float ringScale     = displayRadius * kRingScaleMultiplier;
        glm::mat4 ringModel = glm::translate(glm::mat4(1.0f), body.renderPosition());
        ringModel = glm::scale(ringModel, glm::vec3(ringScale));
        ringShader_.setMat4 ("model",      ringModel);
        ringShader_.setVec3 ("bodyCenter", body.renderPosition());
        ringShader_.setFloat("bodyRadius", displayRadius);
        glDrawArrays(GL_TRIANGLE_STRIP, 0, ringVertexCount_);
    }
    glDepthMask(GL_TRUE);
    glBindVertexArray(0);
}

void Application::renderTrails(const glm::mat4& view, const glm::mat4& projection)
{
    trailShader_.use();
    trailShader_.setMat4("view",       view);
    trailShader_.setMat4("projection", projection);

    glBindVertexArray(trailVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, trailVBO_);
    glDepthMask(GL_FALSE);

    std::vector<glm::vec3> trailUploadBuffer;
    for (const auto& body : bodies_)
    {
        if (body.trailPoints.size() < 2) continue;
        trailUploadBuffer.assign(body.trailPoints.begin(), body.trailPoints.end());
        glBufferData(GL_ARRAY_BUFFER,
                     trailUploadBuffer.size() * sizeof(glm::vec3),
                     trailUploadBuffer.data(),
                     GL_DYNAMIC_DRAW);
        trailShader_.setVec3("trailColor", body.color);
        trailShader_.setInt ("pointCount", static_cast<int>(trailUploadBuffer.size()));
        glDrawArrays(GL_LINE_STRIP, 0, static_cast<GLsizei>(trailUploadBuffer.size()));
    }
    glDepthMask(GL_TRUE);
    glBindVertexArray(0);
}

void Application::renderAtmospheres(const glm::mat4& view, const glm::mat4& projection)
{
    if (bodies_.empty()) return;

    const glm::vec3 lightPosition = bodies_[0].renderPosition();

    atmosphereShader_.use();
    atmosphereShader_.setMat4("view",       view);
    atmosphereShader_.setMat4("projection", projection);
    atmosphereShader_.setVec3("lightPos",   lightPosition);
    atmosphereShader_.setVec3("viewPos",    camera_.getPosition());

    // Translucent shell — depth-test against the scene (so it occludes
    // correctly when planets pass in front), but don't write depth so
    // overlapping atmospheres blend cleanly.
    glDepthMask(GL_FALSE);

    for (const auto& body : bodies_)
    {
        if (!body.hasAtmosphere) continue;

        const float shellScale = body.displayScale * (1.0f + body.atmosphereHeight);
        glm::mat4   model      = glm::translate(glm::mat4(1.0f), body.renderPosition());
        model                  = glm::scale(model, glm::vec3(shellScale));

        atmosphereShader_.setMat4 ("model",           model);
        atmosphereShader_.setVec3 ("atmosphereColor", body.atmosphereColor);
        atmosphereShader_.setFloat("density",         body.atmosphereDensity);

        body.mesh.draw();
    }

    glDepthMask(GL_TRUE);
}

void Application::renderPlacementHint(const glm::mat4& view, const glm::mat4& projection)
{
    const glm::vec3 startPos = uiManager_.getPlacementStart();
    const glm::vec3 endPos   = uiManager_.getPlacementEnd();
    if (glm::length(endPos - startPos) < 0.1f) return;  // no drag yet

    const std::vector<glm::vec3> points = { startPos, endPos };

    trailShader_.use();
    trailShader_.setMat4("view",       view);
    trailShader_.setMat4("projection", projection);
    trailShader_.setVec3("trailColor", glm::vec3(1.0f, 0.85f, 0.25f));  // amber
    trailShader_.setInt ("pointCount", static_cast<int>(points.size()));

    glBindVertexArray(trailVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, trailVBO_);
    glBufferData(GL_ARRAY_BUFFER, points.size() * sizeof(glm::vec3),
                 points.data(), GL_DYNAMIC_DRAW);

    glDepthMask(GL_FALSE);
    glLineWidth(3.0f);
    glDrawArrays(GL_LINE_STRIP, 0, static_cast<GLsizei>(points.size()));
    glLineWidth(1.0f);
    glDepthMask(GL_TRUE);
    glBindVertexArray(0);
}

void Application::renderLagrange(const glm::mat4& view, const glm::mat4& projection)
{
    if (bodies_.size() < 2) return;
    const int selectedIdx = uiManager_.getSelectedPlanetIndex();
    if (selectedIdx <= 0 || selectedIdx >= static_cast<int>(bodies_.size())) return;

    // Primary = the most massive body. Conventionally bodies_[0] (the Sun),
    // but search to stay correct in alternative presets (Trappist-1, binary).
    int    primaryIdx = 0;
    double maxMass    = bodies_[0].mass_kg;
    for (size_t i = 1; i < bodies_.size(); ++i)
    {
        if (bodies_[i].mass_kg > maxMass)
        {
            maxMass    = bodies_[i].mass_kg;
            primaryIdx = static_cast<int>(i);
        }
    }
    if (primaryIdx == selectedIdx) return;  // can't compute against itself

    const lagrange::Points points = lagrange::compute(bodies_[primaryIdx], bodies_[selectedIdx]);
    if (!points.valid) return;

    // L1 is intentionally lime / yellow-green so it doesn't blend with the
    // Sun's warm yellow when both end up in frame.
    static constexpr glm::vec3 kColors[5] = {
        glm::vec3(0.70f, 1.00f, 0.20f),  // L1 — lime green
        glm::vec3(1.00f, 0.55f, 0.15f),  // L2 — orange
        glm::vec3(1.00f, 0.25f, 0.25f),  // L3 — red
        glm::vec3(0.25f, 0.95f, 0.95f),  // L4 — cyan (stable)
        glm::vec3(0.95f, 0.25f, 0.95f),  // L5 — magenta (stable)
    };

    // Marker radius proportional to body separation so it stays readable
    // across Sun-Earth (1 AU) and Sun-Mercury (0.4 AU) scales alike.
    const float separationWU = glm::length(
        bodies_[selectedIdx].renderPosition() - bodies_[primaryIdx].renderPosition());
    const float markerRadius = std::max(0.5f, separationWU * 0.012f);

    bodyShader_.use();
    bodyShader_.setMat4 ("view",          view);
    bodyShader_.setMat4 ("projection",    projection);
    bodyShader_.setVec3 ("lightPos",      bodies_[primaryIdx].renderPosition());
    bodyShader_.setVec3 ("viewPos",       camera_.getPosition());
    bodyShader_.setFloat("emissive",      1.0f);  // skip lighting, output color directly
    bodyShader_.setInt  ("hasRingShadow", 0);

    for (int i = 0; i < 5; ++i)
    {
        glm::mat4 model = glm::translate(glm::mat4(1.0f), points.positions[i]);
        model           = glm::scale(model, glm::vec3(markerRadius));
        bodyShader_.setMat4("model",       model);
        bodyShader_.setVec3("planetColor", kColors[i]);
        lagrangeMesh_.draw();
    }
}

void Application::renderPathPrediction(const glm::mat4& view, const glm::mat4& projection)
{
    const auto& path = pathPredictor_.getPath();
    if (path.size() < 2) return;

    // Reverse so the line fades bright-near-body, dim-toward-horizon
    // (the trail shader's vT goes 0→1 across vertex index, with higher
    // alpha at vT=1).
    std::vector<glm::vec3> uploadBuffer(path.rbegin(), path.rend());

    trailShader_.use();
    trailShader_.setMat4("view",       view);
    trailShader_.setMat4("projection", projection);
    trailShader_.setVec3("trailColor", kPredictionColor);
    trailShader_.setInt ("pointCount", static_cast<int>(uploadBuffer.size()));

    glBindVertexArray(trailVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, trailVBO_);
    glBufferData(GL_ARRAY_BUFFER,
                 uploadBuffer.size() * sizeof(glm::vec3),
                 uploadBuffer.data(),
                 GL_DYNAMIC_DRAW);

    glDepthMask(GL_FALSE);
    glLineWidth(2.0f);   // visually distinct from the 1px-wide trails
    glDrawArrays(GL_LINE_STRIP, 0, static_cast<GLsizei>(uploadBuffer.size()));
    glLineWidth(1.0f);
    glDepthMask(GL_TRUE);
    glBindVertexArray(0);
}

void Application::renderBloomPasses(const glm::mat4& view, const glm::mat4& projection,
                                    GLuint& outBlurredTexture)
{
    // ---- Bright pass: render emissive bodies into bloomPingFbo_ ----------
    bloomPingFbo_.bind();
    glViewport(0, 0, bloomPingFbo_.width(), bloomPingFbo_.height());
    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    glDisable(GL_DEPTH_TEST);
    bodyShader_.use();
    bodyShader_.setMat4("view",       view);
    bodyShader_.setMat4("projection", projection);
    bodyShader_.setMat4("model",      glm::mat4(1.0f));
    bodyShader_.setVec3("lightPos",   glm::vec3(0.0f));  // unused in emissive branch
    bodyShader_.setVec3("viewPos",    camera_.getPosition());

    for (const auto& body : bodies_)
    {
        if (body.emissive < 0.5f) continue;
        body.render(bodyShader_);
    }

    // ---- Ping-pong Gaussian blur ----------------------------------------
    constexpr int kBlurPasses = 10;
    bloomBlurShader_.use();
    bloomBlurShader_.setInt("source", 0);
    glActiveTexture(GL_TEXTURE0);
    glBindVertexArray(fullscreenQuadVAO_);

    Framebuffer* readFb  = &bloomPingFbo_;
    Framebuffer* writeFb = &bloomPongFbo_;
    bool         horizontal = true;

    for (int pass = 0; pass < kBlurPasses; ++pass)
    {
        writeFb->bind();
        glViewport(0, 0, writeFb->width(), writeFb->height());
        bloomBlurShader_.setInt("horizontal", horizontal ? 1 : 0);
        glBindTexture(GL_TEXTURE_2D, readFb->colorTexture());
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

        std::swap(readFb, writeFb);
        horizontal = !horizontal;
    }

    outBlurredTexture = readFb->colorTexture();

    glBindVertexArray(0);
    glEnable(GL_DEPTH_TEST);
}

void Application::renderComposite(GLuint blurredBloomTexture, int viewportWidth, int viewportHeight)
{
    Framebuffer::bindDefault();
    glViewport(0, 0, viewportWidth, viewportHeight);
    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    glDisable(GL_DEPTH_TEST);
    bloomCompositeShader_.use();
    bloomCompositeShader_.setInt  ("scene",          0);
    bloomCompositeShader_.setInt  ("bloom",          1);
    bloomCompositeShader_.setFloat("bloomIntensity", uiManager_.showBloom ? 1.5f : 0.0f);

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, sceneResolveFbo_.colorTexture());
    glActiveTexture(GL_TEXTURE1);
    glBindTexture(GL_TEXTURE_2D, blurredBloomTexture);
    glActiveTexture(GL_TEXTURE0);   // restore unit 0

    glBindVertexArray(fullscreenQuadVAO_);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    glBindVertexArray(0);
    glEnable(GL_DEPTH_TEST);
}
