#include "core/Application.h"

#include "core/Constants.h"
#include "core/Screenshot.h"
#include "EmbeddedShaders.h"   // auto-generated by CMake from shaders/*.glsl
#include "imgui/imgui.h"
#include "imgui/backends/imgui_impl_glfw.h"
#include "imgui/backends/imgui_impl_opengl3.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <ctime>
#include <filesystem>
#include <string>

namespace
{
// Trail sampling tuning.
constexpr size_t kTrailHistoryCapacity = 512;
constexpr float  kMinimumTrailStepWU   = 0.2f;
constexpr float  kTrailTeleportJumpWU  = 100.0f;

// Procedural ring mesh tuning.
constexpr int    kRingSegmentCount   = 64;
constexpr float  kRingInnerRadius    = 1.0f;
constexpr float  kRingOuterRadius    = 1.5f;
constexpr float  kRingScaleMultiplier = 1.5f;

// Camera and projection defaults.
const     glm::vec3 kInitialCameraPosition{ 0.0f, 0.0f, 300.0f };
constexpr float  kProjectionNearPlane     = 0.01f;
constexpr float  kProjectionFarPlane      = 10000.0f;

// Scratch-vector reserve (prevents reallocations during typical "Add Planet" sessions).
constexpr size_t kBodiesReserveCapacity = 16;

// Path prediction tuning.
constexpr int    kPredictionSampleCount    = 500;
constexpr int    kPredictionRefreshFrames  = 30;   // Recompute roughly twice per second.
const     glm::vec3 kPredictionColor{ 0.55f, 0.95f, 1.0f };

// Visual ring color.
const     glm::vec3 kSaturnRingColor{ 0.90f, 0.85f, 0.70f };
} // namespace

//----------------------------------------------------------------------------
// Static callbacks
//----------------------------------------------------------------------------

Application* Application::fromWindow(GLFWwindow* window)
{
    return static_cast<Application*>(glfwGetWindowUserPointer(window));
}

void Application::mouseCallback(GLFWwindow* window, double xpos, double ypos)
{
    Application* app = fromWindow(window);
    if (app == nullptr) return;

    if (app->firstMouseEvent_)
    {
        app->lastMouseX_      = static_cast<float>(xpos);
        app->lastMouseY_      = static_cast<float>(ypos);
        app->firstMouseEvent_ = false;
    }

    const float xOffset = static_cast<float>(xpos) - app->lastMouseX_;
    const float yOffset = app->lastMouseY_ - static_cast<float>(ypos);
    app->lastMouseX_    = static_cast<float>(xpos);
    app->lastMouseY_    = static_cast<float>(ypos);

    if (app->uiManager_.isRightMousePressed(window))
    {
        app->camera_.processMouseMovement(xOffset, yOffset);
    }
}

void Application::scrollCallback(GLFWwindow* window, double /*xoffset*/, double yoffset)
{
    Application* app = fromWindow(window);
    if (app == nullptr || ImGui::GetIO().WantCaptureMouse) return;

    app->camera_.processKeyboard(yoffset > 0 ? GLFW_KEY_W : GLFW_KEY_S, 0.1f);
}

void Application::windowFocusCallback(GLFWwindow* window, int focused)
{
    Application* app = fromWindow(window);
    if (app == nullptr) return;

    if (focused == GLFW_FALSE)
    {
        // Only auto-pause if the simulation is actively running and isn't
        // already paused (so manual pauses don't get clobbered on resume).
        if (app->appState_ == AppState::Running && !app->physics_.paused)
        {
            app->physics_.paused = true;
            app->wasAutoPaused_  = true;
        }
    }
    else if (app->wasAutoPaused_)
    {
        app->physics_.paused = false;
        app->wasAutoPaused_  = false;
    }
}

void Application::windowCloseCallback(GLFWwindow* window)
{
    Application* app = fromWindow(window);
    if (app == nullptr) return;

    if (app->appState_ == AppState::Running)
    {
        // Defer the close until the user confirms.
        glfwSetWindowShouldClose(window, GLFW_FALSE);
        app->openQuitPopup_ = true;
    }
}

void Application::framebufferSizeCallback(GLFWwindow* window, int width, int height)
{
    glViewport(0, 0, width, height);
    Application* app = fromWindow(window);
    if (app == nullptr) return;
    app->sceneFbo_.resize(width, height);
    app->bloomPingFbo_.resize(width / 2, height / 2);
    app->bloomPongFbo_.resize(width / 2, height / 2);
}

//----------------------------------------------------------------------------
// Construction / destruction
//----------------------------------------------------------------------------

Application::Application(int windowWidth, int windowHeight, const char* title)
    : window_(windowWidth, windowHeight, title)
    , camera_(kInitialCameraPosition)
    , bodyShader_           (embedded_shaders::VertexShader,           embedded_shaders::FragmentShader)
    , gridShader_           (embedded_shaders::GridVertexShader,       embedded_shaders::GridFragmentShader)
    , trailShader_          (embedded_shaders::TrailVertexShader,      embedded_shaders::TrailFragmentShader)
    , skyShader_            (embedded_shaders::SkyVertexShader,        embedded_shaders::SkyFragmentShader)
    , ringShader_           (embedded_shaders::RingVertexShader,       embedded_shaders::RingFragmentShader)
    , bloomBlurShader_      (embedded_shaders::FullscreenQuadVertexShader, embedded_shaders::BloomBlurFragmentShader)
    , bloomCompositeShader_ (embedded_shaders::FullscreenQuadVertexShader, embedded_shaders::BloomCompositeFragmentShader)
    , sceneFbo_             (windowWidth,     windowHeight,     true)
    , bloomPingFbo_         (windowWidth / 2, windowHeight / 2, false)
    , bloomPongFbo_         (windowWidth / 2, windowHeight / 2, false)
    , physics_()
    , uiManager_()
    , grid_(10000.0f, 200, 0.0f)
{
    bodies_.reserve(kBodiesReserveCapacity);

    GLFWwindow* glfwWindow = window_.getGLFWwindow();
    glfwSetWindowUserPointer(glfwWindow, this);
    glfwSetFramebufferSizeCallback(glfwWindow, framebufferSizeCallback);
    glfwSetCursorPosCallback(glfwWindow,       mouseCallback);
    glfwSetScrollCallback(glfwWindow,          scrollCallback);
    glfwSetWindowFocusCallback(glfwWindow,     windowFocusCallback);
    glfwSetWindowCloseCallback(glfwWindow,     windowCloseCallback);
    glfwSetInputMode(glfwWindow, GLFW_CURSOR, GLFW_CURSOR_NORMAL);

    // HiDPI: the constructor's windowWidth/Height are window units; the actual
    // pixel framebuffer may differ. Resize FBOs to match the framebuffer.
    int initialFbWidth = 0, initialFbHeight = 0;
    glfwGetFramebufferSize(glfwWindow, &initialFbWidth, &initialFbHeight);
    if (initialFbWidth != windowWidth || initialFbHeight != windowHeight)
    {
        sceneFbo_.resize(initialFbWidth, initialFbHeight);
        bloomPingFbo_.resize(initialFbWidth / 2, initialFbHeight / 2);
        bloomPongFbo_.resize(initialFbWidth / 2, initialFbHeight / 2);
    }

    glEnable(GL_DEPTH_TEST);
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    createAuxiliaryBuffers();
    // Bodies are deferred to startSimulation() — the menu screen runs first
    // and only loads the default solar system when the user clicks Start.

    ImGui::CreateContext();
    ImGui_ImplGlfw_InitForOpenGL(glfwWindow, true);
    ImGui_ImplOpenGL3_Init("#version 330");

    glfwSwapInterval(uiManager_.vsync ? 1 : 0);
}

Application::~Application()
{
    destroyAuxiliaryBuffers();
    ImGui_ImplOpenGL3_Shutdown();
    ImGui_ImplGlfw_Shutdown();
    ImGui::DestroyContext();
}

//----------------------------------------------------------------------------
// Public API
//----------------------------------------------------------------------------

void Application::run()
{
    while (!glfwWindowShouldClose(window_.getGLFWwindow()))
    {
        tick();
    }
}

//----------------------------------------------------------------------------
// Frame loop
//----------------------------------------------------------------------------

void Application::tick()
{
    const float currentFrameTime = static_cast<float>(glfwGetTime());
    const float deltaTime        = currentFrameTime - previousFrameTime_;
    previousFrameTime_ = currentFrameTime;

    if (appState_ == AppState::Menu)
    {
        renderMenuFrame(deltaTime);
        return;
    }

    GLFWwindow* glfwWindow = window_.getGLFWwindow();
    if (glfwGetKey(glfwWindow, GLFW_KEY_W) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_W, deltaTime);
    if (glfwGetKey(glfwWindow, GLFW_KEY_S) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_S, deltaTime);
    if (glfwGetKey(glfwWindow, GLFW_KEY_A) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_A, deltaTime);
    if (glfwGetKey(glfwWindow, GLFW_KEY_D) == GLFW_PRESS) camera_.processKeyboard(GLFW_KEY_D, deltaTime);

    handleHotkeys();

    // Advance the simulation FIRST, then snap the orbital camera onto the
    // freshly integrated body position. Doing this in the reverse order
    // left the camera reading the previous-frame target while bodies
    // rendered at their new positions — fast inner planets visibly
    // "teleported" relative to the orbital camera every frame.
    physics_.update(bodies_, static_cast<double>(deltaTime));
    sampleOrbitTrails();
    refreshOrbitalCameraTarget();
    camera_.update(deltaTime);

    // Refresh the path prediction (throttled) so the dashed line stays in
    // sync with the live simulation without paying its O(N² × samples)
    // cost on every frame.
    const int  predSelected = uiManager_.getSelectedPlanetIndex();
    const bool predValid    = uiManager_.showPathPrediction
                              && predSelected >= 0
                              && predSelected < static_cast<int>(bodies_.size());
    if (predValid)
    {
        if (framesSinceLastPrediction_ >= kPredictionRefreshFrames)
        {
            const double horizon = PathPredictor::estimateOrbitalPeriod(bodies_, predSelected);
            pathPredictor_.recompute(bodies_, predSelected, horizon, kPredictionSampleCount);
            framesSinceLastPrediction_ = 0;
        }
        else
        {
            ++framesSinceLastPrediction_;
        }
    }
    else
    {
        pathPredictor_.clear();
        framesSinceLastPrediction_ = kPredictionRefreshFrames;  // force refresh on re-enable
    }

    int framebufferWidth = 0, framebufferHeight = 0;
    glfwGetFramebufferSize(glfwWindow, &framebufferWidth, &framebufferHeight);
    const float aspectRatio = static_cast<float>(framebufferWidth)
                            / static_cast<float>(std::max(framebufferHeight, 1));
    const glm::mat4 view       = camera_.getViewMatrix();
    const glm::mat4 projection = glm::perspective(glm::radians(fieldOfView_),
                                                  aspectRatio,
                                                  kProjectionNearPlane,
                                                  kProjectionFarPlane);

    // ---- Scene pass: render the full 3D world into sceneFbo_ -----------
    sceneFbo_.bind();
    glViewport(0, 0, sceneFbo_.width(), sceneFbo_.height());
    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    renderSky(view, projection);
    renderBodies(view, projection);
    renderGrid(view, projection);
    renderRings(view, projection);

    if (uiManager_.showTrails)         renderTrails(view, projection);
    if (uiManager_.showPathPrediction) renderPathPrediction(view, projection);

    // ---- Bloom passes: bright-pass emissive bodies, then ping-pong blur -
    GLuint blurredBloomTexture = 0;
    if (uiManager_.showBloom)
    {
        renderBloomPasses(view, projection, blurredBloomTexture);
    }
    else
    {
        bloomPingFbo_.bind();
        glViewport(0, 0, bloomPingFbo_.width(), bloomPingFbo_.height());
        glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        blurredBloomTexture = bloomPingFbo_.colorTexture();
    }

    // ---- Composite: scene + bloom into the default framebuffer ---------
    renderComposite(blurredBloomTexture, framebufferWidth, framebufferHeight);

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();
    uiManager_.render(window_, camera_, deltaTime, bodies_, grid_, physics_);

    if (uiManager_.menuRequested)
    {
        openReturnToMenuPopup_ = true;
        uiManager_.menuRequested = false;
    }
    if (uiManager_.settingsRequested)
    {
        settingsModal_.requestOpen();
        uiManager_.settingsRequested = false;
    }
    if (uiManager_.saveRequested)
    {
        saveLoadModal_.requestOpenSave();
        uiManager_.saveRequested = false;
    }
    if (uiManager_.loadRequested)
    {
        saveLoadModal_.requestOpenLoad();
        uiManager_.loadRequested = false;
    }
    if (uiManager_.addPlanetRequested)
    {
        addPlanetModal_.requestOpen();
        uiManager_.addPlanetRequested = false;
    }

    settingsModal_.render(camera_, fieldOfView_, guiScale_, uiManager_);
    saveLoadModal_.render(bodies_, physics_, camera_, uiManager_);
    addPlanetModal_.render(bodies_, uiManager_);
    renderConfirmModals();

    if (uiManager_.vsyncDirty)
    {
        glfwSwapInterval(uiManager_.vsync ? 1 : 0);
        uiManager_.vsyncDirty = false;
    }

    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    glfwSwapBuffers(glfwWindow);
    glfwPollEvents();
}

//----------------------------------------------------------------------------
// Menu state
//----------------------------------------------------------------------------

void Application::renderMenuFrame(float deltaTime)
{
    menuTime_ += deltaTime;

    GLFWwindow* glfwWindow = window_.getGLFWwindow();

    int framebufferWidth = 0, framebufferHeight = 0;
    glfwGetFramebufferSize(glfwWindow, &framebufferWidth, &framebufferHeight);
    const float aspectRatio = static_cast<float>(framebufferWidth)
                            / static_cast<float>(std::max(framebufferHeight, 1));

    // Slow camera orbit around the origin for a cinematic skybox.
    constexpr float kMenuOrbitRadius      = 300.0f;
    constexpr float kMenuOrbitHeight      = 60.0f;
    constexpr float kMenuOrbitAngularRate = 0.05f;
    const float angle = menuTime_ * kMenuOrbitAngularRate;
    const glm::vec3 menuCameraPosition(kMenuOrbitRadius * std::cos(angle),
                                       kMenuOrbitHeight,
                                       kMenuOrbitRadius * std::sin(angle));

    const glm::mat4 view       = glm::lookAt(menuCameraPosition,
                                             glm::vec3(0.0f),
                                             glm::vec3(0.0f, 1.0f, 0.0f));
    const glm::mat4 projection = glm::perspective(glm::radians(fieldOfView_),
                                                  aspectRatio,
                                                  kProjectionNearPlane,
                                                  kProjectionFarPlane);

    // The menu draws directly to the default framebuffer — no offscreen FBO
    // bounce, no bloom. Bind explicitly so we never inherit a stale binding.
    Framebuffer::bindDefault();
    glViewport(0, 0, framebufferWidth, framebufferHeight);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    renderSky(view, projection);

    ImGui_ImplOpenGL3_NewFrame();
    ImGui_ImplGlfw_NewFrame();
    ImGui::NewFrame();

    const StartMenuAction action = startMenu_.render(framebufferWidth, framebufferHeight);

    if (action == StartMenuAction::Settings)
    {
        settingsModal_.requestOpen();
    }

    // Settings is the only modal we render from the menu — it doesn't depend
    // on the simulation state, only on settings_ + camera_ + uiManager_.
    settingsModal_.render(camera_, fieldOfView_, guiScale_, uiManager_);

    ImGui::Render();
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

    glfwSwapBuffers(glfwWindow);
    glfwPollEvents();

    switch (action)
    {
        case StartMenuAction::Start:    startSimulation(); break;
        case StartMenuAction::Quit:     glfwSetWindowShouldClose(glfwWindow, true); break;
        case StartMenuAction::Load:     /* Not yet wired from the menu. */ break;
        case StartMenuAction::Settings: /* Handled above. */                break;
        case StartMenuAction::None:     break;
    }
}

void Application::startSimulation()
{
    bodies_.clear();
    loadDefaultBodies();
    shiftToBarycenterFrame();
    camera_.reset();
    physics_.reset();
    pathPredictor_.clear();
    framesSinceLastPrediction_ = kPredictionRefreshFrames;
    appState_ = AppState::Running;
    previousFrameTime_ = static_cast<float>(glfwGetTime());
}

void Application::returnToMenu()
{
    bodies_.clear();
    uiManager_.clearSelection();
    camera_.reset();
    physics_.reset();
    pathPredictor_.clear();
    appState_ = AppState::Menu;
    menuTime_ = 0.0f;
    previousFrameTime_ = static_cast<float>(glfwGetTime());
}

void Application::captureScreenshot()
{
    int framebufferWidth = 0, framebufferHeight = 0;
    glfwGetFramebufferSize(window_.getGLFWwindow(), &framebufferWidth, &framebufferHeight);

    namespace fs = std::filesystem;
    const fs::path directory("screenshots");
    std::error_code errorCode;
    fs::create_directories(directory, errorCode);

    const auto now      = std::chrono::system_clock::now();
    const auto wallTime = std::chrono::system_clock::to_time_t(now);
    std::tm    localTime{};
#ifdef _WIN32
    localtime_s(&localTime, &wallTime);
#else
    localtime_r(&wallTime, &localTime);
#endif
    char timestamp[32];
    std::strftime(timestamp, sizeof(timestamp), "%Y-%m-%d_%H-%M-%S", &localTime);

    const std::string filename = std::string("solarsystem_") + timestamp + ".bmp";
    const std::string fullPath = (directory / filename).string();

    if (captureFramebufferToBMP(fullPath, framebufferWidth, framebufferHeight))
    {
        uiManager_.toasts().success("Screenshot saved: " + fullPath);
    }
    else
    {
        uiManager_.toasts().error("Screenshot failed: cannot write " + fullPath);
    }
}

void Application::renderConfirmModals()
{
    constexpr const char* kReturnPopupId = "Return to Menu?";
    constexpr const char* kQuitPopupId   = "Quit Application?";

    if (openReturnToMenuPopup_)
    {
        ImGui::OpenPopup(kReturnPopupId);
        openReturnToMenuPopup_ = false;
    }
    if (openQuitPopup_)
    {
        ImGui::OpenPopup(kQuitPopupId);
        openQuitPopup_ = false;
    }

    const ImVec2 viewportCenter = ImGui::GetMainViewport()->GetCenter();
    constexpr ImVec2 kButtonSize(120.0f, 0.0f);

    ImGui::SetNextWindowPos(viewportCenter, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    if (ImGui::BeginPopupModal(kReturnPopupId, nullptr, ImGuiWindowFlags_AlwaysAutoResize))
    {
        ImGui::TextUnformatted("Discard the current simulation and return to the main menu?");
        ImGui::Spacing();
        if (ImGui::Button("Yes", kButtonSize))
        {
            returnToMenu();
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button("No", kButtonSize))
        {
            ImGui::CloseCurrentPopup();
        }
        ImGui::EndPopup();
    }

    ImGui::SetNextWindowPos(viewportCenter, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    if (ImGui::BeginPopupModal(kQuitPopupId, nullptr, ImGuiWindowFlags_AlwaysAutoResize))
    {
        ImGui::TextUnformatted("Quit SolarSystemGL?");
        ImGui::Spacing();
        if (ImGui::Button("Quit", kButtonSize))
        {
            glfwSetWindowShouldClose(window_.getGLFWwindow(), GLFW_TRUE);
            ImGui::CloseCurrentPopup();
        }
        ImGui::SameLine();
        if (ImGui::Button("Cancel", kButtonSize))
        {
            ImGui::CloseCurrentPopup();
        }
        ImGui::EndPopup();
    }
}

//----------------------------------------------------------------------------
// Initialization helpers
//----------------------------------------------------------------------------

void Application::loadDefaultBodies()
{
    struct DefaultBody
    {
        const char* name;
        double      semiMajorAxisAU;
        double      orbitalVelocityMS;
        double      massKg;
        float       densityKgPerM3;
        glm::vec3   color;
        float       emissive;
        float       displayScale;
        bool        hasRings;
    };

    const DefaultBody defaults[] = {
        { "Sun",      0.000,     0.0, 1.989e30, 1408.0f, glm::vec3(1.00f, 0.90f, 0.30f), 1.0f, 0.4f, false },
        { "Mercury",  0.387, 47900.0, 3.3011e23, 5427.0f, glm::vec3(0.50f, 0.50f, 0.50f), 0.0f, 1.0f, false },
        { "Venus",    0.723, 35000.0, 4.8675e24, 5243.0f, glm::vec3(0.95f, 0.85f, 0.55f), 0.0f, 1.0f, false },
        { "Earth",    1.000, 29780.0, 5.9720e24, 5514.0f, glm::vec3(0.20f, 0.40f, 1.00f), 0.0f, 1.0f, false },
        { "Mars",     1.524, 24100.0, 6.4171e23, 3933.0f, glm::vec3(0.80f, 0.30f, 0.10f), 0.0f, 1.0f, false },
        { "Jupiter",  5.203, 13070.0, 1.8980e27, 1326.0f, glm::vec3(0.90f, 0.70f, 0.40f), 0.0f, 1.0f, false },
        { "Saturn",   9.537,  9680.0, 5.6834e26,  687.0f, glm::vec3(0.95f, 0.85f, 0.50f), 0.0f, 1.0f, true  },
        { "Uranus",  19.191,  6800.0, 8.6810e25, 1271.0f, glm::vec3(0.60f, 0.85f, 0.90f), 0.0f, 1.0f, false },
        { "Neptune", 30.070,  5430.0, 1.0240e26, 1638.0f, glm::vec3(0.30f, 0.40f, 0.85f), 0.0f, 1.0f, false },
    };

    for (const auto& spec : defaults)
    {
        CelestialBody body;
        body.pos_m        = glm::dvec3(spec.semiMajorAxisAU * AU, 0.0, 0.0);
        body.vel_m        = glm::dvec3(0.0, 0.0, spec.orbitalVelocityMS);
        body.mass_kg      = spec.massKg;
        body.name         = spec.name;
        body.color        = spec.color;
        body.density      = spec.densityKgPerM3;
        body.emissive     = spec.emissive;
        body.displayScale = spec.displayScale;
        body.hasRings     = spec.hasRings;
        body.recalculateGeometry();
        bodies_.push_back(std::move(body));
    }
}

void Application::shiftToBarycenterFrame()
{
    glm::dvec3 totalMomentum(0.0);
    double     totalMass = 0.0;
    for (const auto& body : bodies_)
    {
        totalMomentum += body.vel_m * body.mass_kg;
        totalMass     += body.mass_kg;
    }
    if (totalMass <= 0.0) return;

    const glm::dvec3 centerOfMassVelocity = totalMomentum / totalMass;
    for (auto& body : bodies_)
    {
        body.vel_m -= centerOfMassVelocity;
    }
}

void Application::createAuxiliaryBuffers()
{
    // Dynamic VBO for trail line strips (re-uploaded per body per frame).
    glGenVertexArrays(1, &trailVAO_);
    glGenBuffers(1, &trailVBO_);
    glBindVertexArray(trailVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, trailVBO_);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(glm::vec3), nullptr);
    glEnableVertexAttribArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindVertexArray(0);

    // Static fullscreen unit quad — shared by the sky pass and every
    // fullscreen-quad bloom pass (bright-pass / blur / composite).
    const float fullscreenQuadVertices[] = {
        -1.0f, -1.0f,
         1.0f, -1.0f,
        -1.0f,  1.0f,
         1.0f,  1.0f,
    };
    glGenVertexArrays(1, &fullscreenQuadVAO_);
    glGenBuffers(1, &fullscreenQuadVBO_);
    glBindVertexArray(fullscreenQuadVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, fullscreenQuadVBO_);
    glBufferData(GL_ARRAY_BUFFER, sizeof(fullscreenQuadVertices), fullscreenQuadVertices, GL_STATIC_DRAW);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(float), nullptr);
    glEnableVertexAttribArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindVertexArray(0);

    // Ring mesh: triangle strip on the XZ plane, inner radius 1.0, outer 1.5.
    std::vector<glm::vec3> ringVertices;
    ringVertices.reserve(static_cast<size_t>(2 * (kRingSegmentCount + 1)));
    for (int segment = 0; segment <= kRingSegmentCount; ++segment)
    {
        const float angle = 2.0f * 3.14159265358979f
                          * static_cast<float>(segment)
                          / static_cast<float>(kRingSegmentCount);
        const float cosA  = std::cos(angle);
        const float sinA  = std::sin(angle);
        ringVertices.emplace_back(cosA * kRingInnerRadius, 0.0f, sinA * kRingInnerRadius);
        ringVertices.emplace_back(cosA * kRingOuterRadius, 0.0f, sinA * kRingOuterRadius);
    }
    ringVertexCount_ = static_cast<GLsizei>(ringVertices.size());

    glGenVertexArrays(1, &ringVAO_);
    glGenBuffers(1, &ringVBO_);
    glBindVertexArray(ringVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, ringVBO_);
    glBufferData(GL_ARRAY_BUFFER,
                 ringVertices.size() * sizeof(glm::vec3),
                 ringVertices.data(), GL_STATIC_DRAW);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(glm::vec3), nullptr);
    glEnableVertexAttribArray(0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glBindVertexArray(0);
}

void Application::destroyAuxiliaryBuffers()
{
    if (trailVAO_)          glDeleteVertexArrays(1, &trailVAO_);
    if (trailVBO_)          glDeleteBuffers(1, &trailVBO_);
    if (fullscreenQuadVAO_) glDeleteVertexArrays(1, &fullscreenQuadVAO_);
    if (fullscreenQuadVBO_) glDeleteBuffers(1, &fullscreenQuadVBO_);
    if (ringVAO_)           glDeleteVertexArrays(1, &ringVAO_);
    if (ringVBO_)           glDeleteBuffers(1, &ringVBO_);
    trailVAO_ = trailVBO_ = fullscreenQuadVAO_ = fullscreenQuadVBO_ = ringVAO_ = ringVBO_ = 0;
}

//----------------------------------------------------------------------------
// Per-frame helpers
//----------------------------------------------------------------------------

void Application::refreshOrbitalCameraTarget()
{
    const int targetIndex = camera_.getOrbitalTargetIndex();
    if (targetIndex < 0 || targetIndex >= static_cast<int>(bodies_.size())) return;
    camera_.setOrbitalTargetPos(bodies_[targetIndex].renderPosition());
}

void Application::handleHotkeys()
{
    GLFWwindow* glfwWindow = window_.getGLFWwindow();
    const bool keyboardCaptured = ImGui::GetIO().WantCaptureKeyboard;

    const bool spaceDown = glfwGetKey(glfwWindow, GLFW_KEY_SPACE)  == GLFW_PRESS;
    const bool rDown     = glfwGetKey(glfwWindow, GLFW_KEY_R)      == GLFW_PRESS;
    const bool fDown     = glfwGetKey(glfwWindow, GLFW_KEY_F)      == GLFW_PRESS;
    const bool escDown   = glfwGetKey(glfwWindow, GLFW_KEY_ESCAPE) == GLFW_PRESS;
    const bool oneDown   = glfwGetKey(glfwWindow, GLFW_KEY_1)      == GLFW_PRESS;
    const bool twoDown   = glfwGetKey(glfwWindow, GLFW_KEY_2)      == GLFW_PRESS;
    const bool f12Down   = glfwGetKey(glfwWindow, GLFW_KEY_F12)    == GLFW_PRESS;

    // F12 fires regardless of ImGui keyboard capture — screenshots should
    // be available at all times.
    if (f12Down && !wasF12Pressed_) captureScreenshot();
    wasF12Pressed_ = f12Down;

    if (!keyboardCaptured)
    {
        if (spaceDown && !wasSpacePressed_) physics_.paused = !physics_.paused;
        if (rDown     && !wasRPressed_)     camera_.reset();

        if (fDown && !wasFPressed_)
        {
            const int selected = uiManager_.getSelectedPlanetIndex();
            if (selected >= 0 && selected < static_cast<int>(bodies_.size()))
            {
                camera_.startSmoothMove(bodies_[selected].renderPosition(),
                                        bodies_[selected].focusDistance());
            }
        }

        if (escDown && !wasEscPressed_)
        {
            // Two-stage Esc: close info panel first, only prompt to leave the
            // simulation if nothing is selected.
            if (uiManager_.getSelectedPlanetIndex() >= 0)
            {
                uiManager_.clearSelection();
            }
            else
            {
                openReturnToMenuPopup_ = true;
            }
        }

        if (oneDown && !wasOnePressed_) camera_.setMode(CameraMode::FREE);
        if (twoDown && !wasTwoPressed_)
        {
            const int selected = uiManager_.getSelectedPlanetIndex();
            if (selected >= 0 && selected < static_cast<int>(bodies_.size()))
            {
                camera_.flyToOrbital(selected,
                                     bodies_[selected].renderPosition(),
                                     bodies_[selected].focusDistance());
            }
        }
    }

    wasSpacePressed_ = spaceDown;
    wasRPressed_     = rDown;
    wasFPressed_     = fDown;
    wasEscPressed_   = escDown;
    wasOnePressed_   = oneDown;
    wasTwoPressed_   = twoDown;
}

void Application::sampleOrbitTrails()
{
    for (auto& body : bodies_)
    {
        const glm::vec3 currentPosition = body.renderPosition();

        if (!body.trailPoints.empty())
        {
            const float jump = glm::distance(body.trailPoints.back(), currentPosition);
            if (jump > kTrailTeleportJumpWU) body.trailPoints.clear();
        }

        const bool firstSample = body.trailPoints.empty();
        const bool movedEnough = !firstSample
            && glm::distance(body.trailPoints.back(), currentPosition) > kMinimumTrailStepWU;

        if (firstSample || movedEnough)
        {
            body.trailPoints.push_back(currentPosition);
            if (body.trailPoints.size() > kTrailHistoryCapacity)
            {
                body.trailPoints.pop_front();
            }
        }
    }
}

//----------------------------------------------------------------------------
// Render passes
//----------------------------------------------------------------------------

void Application::renderSky(const glm::mat4& view, const glm::mat4& projection)
{
    skyShader_.use();
    skyShader_.setMat4("invView", glm::inverse(view));
    skyShader_.setMat4("invProj", glm::inverse(projection));
    glDisable(GL_DEPTH_TEST);
    glBindVertexArray(fullscreenQuadVAO_);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    glEnable(GL_DEPTH_TEST);
}

void Application::renderBodies(const glm::mat4& view, const glm::mat4& projection)
{
    const glm::vec3 lightPosition = bodies_.empty()
        ? glm::vec3(0.0f)
        : bodies_[0].renderPosition();

    bodyShader_.use();
    bodyShader_.setMat4("view",       view);
    bodyShader_.setMat4("projection", projection);
    bodyShader_.setMat4("model",      glm::mat4(1.0f));
    bodyShader_.setVec3("lightPos",   lightPosition);
    bodyShader_.setVec3("viewPos",    camera_.getPosition());

    const bool       inOrbitalMode    = (camera_.getMode() == CameraMode::ORBITAL);
    const int        orbitalTargetIdx = camera_.getOrbitalTargetIndex();
    for (size_t i = 0; i < bodies_.size(); ++i)
    {
        // The orbital target is always under the cursor's "hover" raycast,
        // so suppress the hover-scale on it — otherwise it visually inflates
        // for the entire duration of orbital mode.
        const bool isOrbitalTarget = inOrbitalMode && (orbitalTargetIdx == static_cast<int>(i));
        const bool highlight       = uiManager_.isHovered(i) && !isOrbitalTarget;
        bodies_[i].render(bodyShader_, highlight);
    }
}

void Application::renderGrid(const glm::mat4& view, const glm::mat4& projection)
{
    gridShader_.use();
    gridShader_.setMat4("view",       view);
    gridShader_.setMat4("projection", projection);
    gridShader_.setMat4("model",      glm::mat4(1.0f));
    grid_.draw(gridShader_, bodies_);
}

void Application::renderRings(const glm::mat4& view, const glm::mat4& projection)
{
    ringShader_.use();
    ringShader_.setMat4("view",       view);
    ringShader_.setMat4("projection", projection);
    ringShader_.setVec3("ringColor",  kSaturnRingColor);

    glBindVertexArray(ringVAO_);
    glDepthMask(GL_FALSE);
    for (const auto& body : bodies_)
    {
        if (!body.hasRings) continue;
        const float displayRadius = body.radius * body.displayScale;
        const float ringScale     = displayRadius * kRingScaleMultiplier;
        glm::mat4 ringModel = glm::translate(glm::mat4(1.0f), body.renderPosition());
        ringModel = glm::scale(ringModel, glm::vec3(ringScale));
        ringShader_.setMat4("model", ringModel);
        glDrawArrays(GL_TRIANGLE_STRIP, 0, ringVertexCount_);
    }
    glDepthMask(GL_TRUE);
    glBindVertexArray(0);
}

void Application::renderTrails(const glm::mat4& view, const glm::mat4& projection)
{
    trailShader_.use();
    trailShader_.setMat4("view",       view);
    trailShader_.setMat4("projection", projection);

    glBindVertexArray(trailVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, trailVBO_);
    glDepthMask(GL_FALSE);

    std::vector<glm::vec3> trailUploadBuffer;
    for (const auto& body : bodies_)
    {
        if (body.trailPoints.size() < 2) continue;
        trailUploadBuffer.assign(body.trailPoints.begin(), body.trailPoints.end());
        glBufferData(GL_ARRAY_BUFFER,
                     trailUploadBuffer.size() * sizeof(glm::vec3),
                     trailUploadBuffer.data(),
                     GL_DYNAMIC_DRAW);
        trailShader_.setVec3("trailColor", body.color);
        trailShader_.setInt ("pointCount", static_cast<int>(trailUploadBuffer.size()));
        glDrawArrays(GL_LINE_STRIP, 0, static_cast<GLsizei>(trailUploadBuffer.size()));
    }
    glDepthMask(GL_TRUE);
    glBindVertexArray(0);
}

void Application::renderPathPrediction(const glm::mat4& view, const glm::mat4& projection)
{
    const auto& path = pathPredictor_.getPath();
    if (path.size() < 2) return;

    // Reverse so the line fades bright-near-body, dim-toward-horizon
    // (the trail shader's vT goes 0→1 across vertex index, with higher
    // alpha at vT=1).
    std::vector<glm::vec3> uploadBuffer(path.rbegin(), path.rend());

    trailShader_.use();
    trailShader_.setMat4("view",       view);
    trailShader_.setMat4("projection", projection);
    trailShader_.setVec3("trailColor", kPredictionColor);
    trailShader_.setInt ("pointCount", static_cast<int>(uploadBuffer.size()));

    glBindVertexArray(trailVAO_);
    glBindBuffer(GL_ARRAY_BUFFER, trailVBO_);
    glBufferData(GL_ARRAY_BUFFER,
                 uploadBuffer.size() * sizeof(glm::vec3),
                 uploadBuffer.data(),
                 GL_DYNAMIC_DRAW);

    glDepthMask(GL_FALSE);
    glLineWidth(2.0f);   // visually distinct from the 1px-wide trails
    glDrawArrays(GL_LINE_STRIP, 0, static_cast<GLsizei>(uploadBuffer.size()));
    glLineWidth(1.0f);
    glDepthMask(GL_TRUE);
    glBindVertexArray(0);
}

void Application::renderBloomPasses(const glm::mat4& view, const glm::mat4& projection,
                                    GLuint& outBlurredTexture)
{
    // ---- Bright pass: render emissive bodies into bloomPingFbo_ ----------
    bloomPingFbo_.bind();
    glViewport(0, 0, bloomPingFbo_.width(), bloomPingFbo_.height());
    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    glDisable(GL_DEPTH_TEST);
    bodyShader_.use();
    bodyShader_.setMat4("view",       view);
    bodyShader_.setMat4("projection", projection);
    bodyShader_.setMat4("model",      glm::mat4(1.0f));
    bodyShader_.setVec3("lightPos",   glm::vec3(0.0f));  // unused in emissive branch
    bodyShader_.setVec3("viewPos",    camera_.getPosition());

    for (const auto& body : bodies_)
    {
        if (body.emissive < 0.5f) continue;
        body.render(bodyShader_, false);
    }

    // ---- Ping-pong Gaussian blur ----------------------------------------
    constexpr int kBlurPasses = 10;
    bloomBlurShader_.use();
    bloomBlurShader_.setInt("source", 0);
    glActiveTexture(GL_TEXTURE0);
    glBindVertexArray(fullscreenQuadVAO_);

    Framebuffer* readFb  = &bloomPingFbo_;
    Framebuffer* writeFb = &bloomPongFbo_;
    bool         horizontal = true;

    for (int pass = 0; pass < kBlurPasses; ++pass)
    {
        writeFb->bind();
        glViewport(0, 0, writeFb->width(), writeFb->height());
        bloomBlurShader_.setInt("horizontal", horizontal ? 1 : 0);
        glBindTexture(GL_TEXTURE_2D, readFb->colorTexture());
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

        std::swap(readFb, writeFb);
        horizontal = !horizontal;
    }

    outBlurredTexture = readFb->colorTexture();

    glBindVertexArray(0);
    glEnable(GL_DEPTH_TEST);
}

void Application::renderComposite(GLuint blurredBloomTexture, int viewportWidth, int viewportHeight)
{
    Framebuffer::bindDefault();
    glViewport(0, 0, viewportWidth, viewportHeight);
    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    glDisable(GL_DEPTH_TEST);
    bloomCompositeShader_.use();
    bloomCompositeShader_.setInt  ("scene",          0);
    bloomCompositeShader_.setInt  ("bloom",          1);
    bloomCompositeShader_.setFloat("bloomIntensity", uiManager_.showBloom ? 1.5f : 0.0f);

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, sceneFbo_.colorTexture());
    glActiveTexture(GL_TEXTURE1);
    glBindTexture(GL_TEXTURE_2D, blurredBloomTexture);
    glActiveTexture(GL_TEXTURE0);   // restore unit 0

    glBindVertexArray(fullscreenQuadVAO_);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    glBindVertexArray(0);
    glEnable(GL_DEPTH_TEST);
}
